<?php
// This file is part of Moodle - https://moodle.org/
//
// Moodle is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// Moodle is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with Moodle.  If not, see <https://www.gnu.org/licenses/>.

/**
 * Strings for component 'countries', language 'en', version '4.0'.
 *
 * @package     countries
 * @category    string
 * @copyright   1999 Martin Dougiamas and contributors
 * @license     https://www.gnu.org/copyleft/gpl.html GNU GPL v3 or later
 */

defined('MOODLE_INTERNAL') || die();

$string['AD'] = 'Андора';
$string['AE'] = 'З\'яднаныя Арабскія Эміраты';
$string['AF'] = 'Афганістан';
$string['AG'] = 'Антыгуа і Барбуда';
$string['AI'] = 'Ангільля';
$string['AL'] = 'Албанія';
$string['AM'] = 'Арменія';
$string['AO'] = 'Ангола';
$string['AQ'] = 'Антарктыда';
$string['AR'] = 'Аргентына';
$string['AS'] = 'Амерыканскае Самоа';
$string['AT'] = 'Аўстрыя';
$string['AU'] = 'Аўстралія';
$string['AW'] = 'Аруба';
$string['AX'] = 'Аландзкія Выспы';
$string['AZ'] = 'Азербайджан';
$string['BA'] = 'Босьнія і Герцагавіна';
$string['BB'] = 'Барбадас';
$string['BD'] = 'Бангладэш';
$string['BE'] = 'Бельгія';
$string['BF'] = 'Буркіна Фасо';
$string['BG'] = 'Балгарыя';
$string['BH'] = 'Бахрэйн';
$string['BI'] = 'Бурундзі';
$string['BJ'] = 'Бэнін';
$string['BL'] = 'Сэнт-Бартэлемі';
$string['BM'] = 'Бермуды';
$string['BN'] = 'Брунэй-Дарусалам';
$string['BO'] = 'Балівія (Шматнацыйнае Панства)';
$string['BQ'] = 'Банайрэ, Сінт-Эстатыус і Саба';
$string['BR'] = 'Бразілія';
$string['BS'] = 'Багамы';
$string['BT'] = 'Бутан';
$string['BV'] = 'Выспа Бувэ';
$string['BW'] = 'Батсвана';
$string['BY'] = 'Беларусь';
$string['BZ'] = 'Беліз';
$string['CA'] = 'Канада';
$string['CC'] = 'Какосавыя Выспы (Кілінг)';
$string['CD'] = 'Конга (Дэмакратычная Рэспубліка)';
$string['CF'] = 'Цэнтральна-Афрыканская Рэспубліка';
$string['CG'] = 'Конга';
$string['CH'] = 'Швейцарыя';
$string['CI'] = 'Кот-д\'Івуар';
$string['CK'] = 'Выспы Кука';
$string['CL'] = 'Чылі';
$string['CM'] = 'Камерун';
$string['CN'] = 'Кітай';
$string['CO'] = 'Калумбія';
$string['CR'] = 'Коста Рыка';
$string['CU'] = 'Куба';
$string['CV'] = 'Каба Вэрдэ';
$string['CW'] = 'Кюрасаа';
$string['CX'] = 'Выспа Колядаў';
$string['CY'] = 'Кіпр';
$string['CZ'] = 'Чэхія';
$string['DE'] = 'Германія';
$string['DJ'] = 'Джыбуці';
$string['DK'] = 'Данія';
$string['DM'] = 'Дамініка';
$string['DO'] = 'Дамініканская Рэспубліка';
$string['DZ'] = 'Алжыр';
$string['EC'] = 'Эквадор';
$string['EE'] = 'Эстонія';
$string['EG'] = 'Егіпет';
$string['EH'] = 'Заходняя Сахара';
$string['ER'] = 'Эрытрэя';
$string['ES'] = 'Гішпанія';
$string['ET'] = 'Эфіёпія';
$string['FI'] = 'Фінляндыя';
$string['FJ'] = 'Фіджы';
$string['FK'] = 'Фалклэндскія выспы (Мальвіны)';
$string['FM'] = 'Мікранэзія (Федэратыўныя Штаты)';
$string['FO'] = 'Фарэрскія Выспы';
$string['FR'] = 'Францыя';
$string['GA'] = 'Габон';
$string['GB'] = 'З\'яднанае Каралеўства';
$string['GD'] = 'Грэнада';
$string['GE'] = 'Картвэлія (Грузія)';
$string['GF'] = 'Французкая Гвіяна';
$string['GG'] = 'Гернси';
$string['GH'] = 'Гана';
$string['GI'] = 'Гібралтар';
$string['GL'] = 'Грэнландыя';
$string['GM'] = 'Гамбія';
$string['GN'] = 'Гвінея';
$string['GP'] = 'Гвадэлупа';
$string['GQ'] = 'Экватарная Гвінея';
$string['GR'] = 'Грэцыя';
$string['GS'] = 'Паўднёвая Георгія і Паўднёвыя Сандвічавы Выспы';
$string['GT'] = 'Гватэмала';
$string['GU'] = 'Гуам';
$string['GW'] = 'Гвінея-Бісау';
$string['GY'] = 'Гвіяна';
$string['HK'] = 'Ганконг';
$string['HM'] = 'Выспа Херд і Выспы Макдональда';
$string['HN'] = 'Гандурас';
$string['HR'] = 'Харватыя';
$string['HT'] = 'Гаіці';
$string['HU'] = 'Вугорыя (Венгрыя)';
$string['ID'] = 'Інданэзія';
$string['IE'] = 'Ірландыя';
$string['IL'] = 'Ізраіль';
$string['IM'] = 'Выспа Мэн';
$string['IN'] = 'Індыя';
$string['IO'] = 'Брытанская Тэрыторыя Індыйскага Акіяна';
$string['IQ'] = 'Ірак';
$string['IR'] = 'Іран (Ісламская Рэспубліка)';
$string['IS'] = 'Ісландыя';
$string['IT'] = 'Італія';
$string['JE'] = 'Джэрсі';
$string['JM'] = 'Ямайка';
$string['JO'] = 'Іярданія';
$string['JP'] = 'Японія';
$string['KE'] = 'Кенія';
$string['KG'] = 'Кыргызстан';
$string['KH'] = 'Камбоджа';
$string['KI'] = 'Кірыбаці';
$string['KM'] = 'Каморы';
$string['KN'] = 'Сэнт Кітс і Невіс';
$string['KP'] = 'Карэя (Народна-Дэмакратычная Рэспубліка)';
$string['KR'] = 'Карэя (Рэспубліка)';
$string['KW'] = 'Кувейт';
$string['KY'] = 'Кайманавы Выспы';
$string['KZ'] = 'Казахстан';
$string['LA'] = 'Лаоская Народна-Дэмакратычная Рэспубліка';
$string['LB'] = 'Лібан';
$string['LC'] = 'Санкт Люсія';
$string['LI'] = 'Ліхтэнштэйн';
$string['LK'] = 'Шры Ланка';
$string['LR'] = 'Ліберыя';
$string['LS'] = 'Лесота';
$string['LT'] = 'Літва';
$string['LU'] = 'Люксембург';
$string['LV'] = 'Латвія';
$string['LY'] = 'Лібія';
$string['MA'] = 'Марока';
$string['MC'] = 'Манака';
$string['MD'] = 'Малдова (Рэспубліка)';
$string['ME'] = 'Чарнагорыя';
$string['MF'] = 'Сэнт-Марцін (Французкая Частка)';
$string['MG'] = 'Мадагаскар';
$string['MH'] = 'Маршалавы Выспы';
$string['MK'] = 'Паўночная Македонія';
$string['ML'] = 'Малі';
$string['MM'] = 'М\'янма';
$string['MN'] = 'Манголія';
$string['MO'] = 'Макаа';
$string['MP'] = 'Паўночныя Марыянскія Выспы';
$string['MQ'] = 'Марцініка';
$string['MR'] = 'Маўрытанія';
$string['MS'] = 'Мантсэрат';
$string['MT'] = 'Мальта';
$string['MU'] = 'Маўрыкій';
$string['MV'] = 'Мальдывы';
$string['MW'] = 'Малаві';
$string['MX'] = 'Мексіка';
$string['MY'] = 'Малайзія';
$string['MZ'] = 'Мазамбік';
$string['NA'] = 'Намібія';
$string['NC'] = 'Новая Калядонія';
$string['NE'] = 'Нігер';
$string['NF'] = 'Выспа Норфалк';
$string['NG'] = 'Нігерыя';
$string['NI'] = 'Нікарагуа';
$string['NL'] = 'Нідэрланды';
$string['NO'] = 'Нарвегія';
$string['NP'] = 'Непал';
$string['NR'] = 'Науру';
$string['NU'] = 'Ніуэ';
$string['NZ'] = 'Новая Зеландыя';
$string['OM'] = 'Аман';
$string['PA'] = 'Панама';
$string['PE'] = 'Перу';
$string['PF'] = 'Французкая Палінэзія';
$string['PG'] = 'Папуа Новая Гвінея';
$string['PH'] = 'Філіпіны';
$string['PK'] = 'Пакістан';
$string['PL'] = 'Польшча';
$string['PM'] = 'Сэнт-П\'ер і Мікелон';
$string['PN'] = 'Піткэрн';
$string['PR'] = 'Пуэрта Рыка';
$string['PS'] = 'Палестына, Панства';
$string['PT'] = 'Партугалія';
$string['PW'] = 'Палау';
$string['PY'] = 'Парагвай';
$string['QA'] = 'Катар';
$string['RE'] = 'Рэюньён';
$string['RO'] = 'Румынія';
$string['RS'] = 'Сербія';
$string['RU'] = 'Расейская Федэрацыя';
$string['RW'] = 'Руанда';
$string['SA'] = 'Саудаўская Арабія';
$string['SB'] = 'Саламонавы Выспы';
$string['SC'] = 'Сейшэлы';
$string['SD'] = 'Судан';
$string['SE'] = 'Швецыя';
$string['SG'] = 'Сінгапур';
$string['SH'] = 'Выспа Сьвятой Хэлены, Ушэсьця і Трыстан да Кунья';
$string['SI'] = 'Славенія';
$string['SJ'] = 'Шпіцберген і Ян-Маен';
$string['SK'] = 'Славакія';
$string['SL'] = 'Сьера Леонэ';
$string['SM'] = 'Сан Марына';
$string['SN'] = 'Сенегал';
$string['SO'] = 'Самалі';
$string['SR'] = 'Сурынам';
$string['SS'] = 'Паўднёвы Судан';
$string['ST'] = 'Сао-Тамэ і Прынсіпі';
$string['SV'] = 'Эль Сальвадор';
$string['SX'] = 'Сінт-Мартэн (Нідэрландзкая Частка)';
$string['SY'] = 'Сірыйская Арабская Рэспубліка';
$string['SZ'] = 'Эсваціні';
$string['TC'] = 'Выспы Цёркс і Кайкас';
$string['TD'] = 'Чад';
$string['TF'] = 'Французкія Паўднёвыя Тэрыторыі';
$string['TG'] = 'Тога';
$string['TH'] = 'Тайланд';
$string['TJ'] = 'Таджыкістан';
$string['TK'] = 'Такелау';
$string['TL'] = 'Тымор-Лешці';
$string['TM'] = 'Туркменістан';
$string['TN'] = 'Туніс';
$string['TO'] = 'Тонга';
$string['TR'] = 'Турцыя';
$string['TT'] = 'Трынідад і Табага';
$string['TV'] = 'Тувалу';
$string['TW'] = 'Тайвань';
$string['TZ'] = 'Танзанія, З\'яднаная Рэспубліка';
$string['UA'] = 'Украіна';
$string['UG'] = 'Уганда';
$string['UM'] = 'Малыя Аддаленыя Выспы ЗША';
$string['US'] = 'Злучаныя Штаты';
$string['UY'] = 'Уругвай';
$string['UZ'] = 'Узьбекістан';
$string['VA'] = 'Сьвяты Прастол';
$string['VC'] = 'Сьвяты Вінсэнт і Грэнадзіны';
$string['VE'] = 'Венесуэла (Баліварыянская Рэспубліка)';
$string['VG'] = 'Віргінскія Выспы (Брытанскія)';
$string['VI'] = 'Віргінскія Выспы (ЗША)';
$string['VN'] = 'В\'етнам';
$string['VU'] = 'Вануату';
$string['WF'] = 'Ўоліс і Футуна';
$string['WS'] = 'Самоа';
$string['YE'] = 'Емен';
$string['YT'] = 'Маёта';
$string['ZA'] = 'Паўднёвая Афрыка';
$string['ZM'] = 'Замбія';
$string['ZW'] = 'Зімбабвэ';
