<?php
// This file is part of Moodle - https://moodle.org/
//
// Moodle is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// Moodle is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with Moodle.  If not, see <https://www.gnu.org/licenses/>.

/**
 * Strings for component 'message', language 'en', version '4.0'.
 *
 * @package     message
 * @category    string
 * @copyright   1999 Martin Dougiamas and contributors
 * @license     https://www.gnu.org/copyleft/gpl.html GNU GPL v3 or later
 */

defined('MOODLE_INTERNAL') || die();

$string['acceptandaddcontact'] = 'Прыняць і дадаць у кантакты';
$string['addcontact'] = 'Дадаць кантакт';
$string['addcontactconfirm'] = 'Вы ўпэўнены, што жадаеце дадаць {$a} да вашых кантактаў?';
$string['addtofavourites'] = 'Пачаць гутарку';
$string['addtoyourcontacts'] = 'Дадаць да кантактаў';
$string['addtoyourcontactsandmessage'] = 'Дадаць да кантактаў і паведамленьняў';
$string['ago'] = '{$a} таму';
$string['allusers'] = 'Усе паведамленьні ад усіх карыстальнікаў';
$string['backto'] = 'Вярнуцца да {$a}';
$string['backupmessageshelp'] = 'Калі ўключана, імгненныя паведамленьні будуць даданы ў аўтаматычныя рэзервовыя копіі САЙТУ';
$string['blockcontact'] = 'Блакаваць кантакты';
$string['blockedusers'] = 'Блакаваныя карыстальнікі';
$string['blocknoncontacts'] = 'Забараніць не кантактам паведамляць мне';
$string['blockuser'] = 'Блакаваць карыстальніка';
$string['blockuserconfirm'] = 'Вы ўпэўнены, што жадаеце заблакаваць {$a}?';
$string['blockuserconfirmbutton'] = 'Заблакаваць';
$string['cancelselection'] = 'Скасаваць абраньне паведамленьняў';
$string['cantblockuser'] = 'Вы ня можаце блакаваць {$a}, бо ня маеце ролі з дазволам паведамляць ўсім карыстальнікам.';
$string['contactableprivacy'] = 'Прыняць паведамленьне ад:';
$string['contactableprivacy_coursemember'] = 'Мае кантакты і ўсе з маіх курсаў';
$string['contactableprivacy_onlycontacts'] = 'Толькі мае кантакты';
$string['contactableprivacy_site'] = 'Усе на гэтым сайце';
$string['contactblocked'] = 'Кантакт заблакаваны';
$string['contactrequests'] = 'Запыты кантакта';
$string['contactrequestsent'] = 'Запыт кантакта адпраўлены';
$string['contacts'] = 'Кантакты';
$string['conversationactions'] = 'Меню дзеяньняў гутаркі';
$string['decline'] = 'Адмовіць';
$string['defaultmessageoutputs'] = 'Налады абвестак';
$string['defaults'] = 'Стандартнае';
$string['deleteallconfirm'] = 'Вы ўпэўнены, што жадаеце выдаліць гэтую гутарку цалкам. Гэтае дзеяньне ня выдаліць гутарку для іншых удзельнікаў.';
$string['deleteallmessages'] = 'Выдаліць усе паведамленьні';
$string['deleteallselfconfirm'] = 'Вы ўпэўнены, што жадаеце выдаліць гэтую асабістую гутарку цалкам?';
$string['deleteconversation'] = 'Выдаліць гутарку';
$string['deleteforeveryone'] = 'Выдаліць для мяне і ўсіх астатніх';
$string['deleteforeveryoneselectedmessagesconfirm'] = 'Вы ўпэўнены, што жадаеце выдаліць абраныя паведамленьні?';
$string['deleteselectedmessages'] = 'Выдаліць абраныя паведамленьні';
$string['deleteselectedmessagesconfirm'] = 'Вы ўпэўнены, што жадаеце выдаліць абраныя паведамленьні? Гэта ня выдаліць іх для астатніх чальцоў гутаркі.';
$string['deleteselectedmessagesconfirmselfconversation'] = 'Вы ўпэўнены, што жадаеце выдаліць абраныя асабістыя паведамленьні?';
$string['disableall'] = 'Адключыць абвесткі';
$string['disabled'] = 'Паведамленьні адключаны на гэтым сайце';
$string['disallowed'] = 'Блакаваньне выключана';
$string['editmessages'] = 'Рэдагаваць паведамленьні';
$string['emailtagline'] = 'Гэта копія паведамленьня адпраўлена вам з "{$a->sitename}". Перайдзіце па {$a->url}, каб адказаць.';
$string['enabled'] = 'Уключана';
$string['errorcallingprocessor'] = 'Памылка выкліка вызначанага выхаду (output)';
$string['errorconversationdoesnotexist'] = 'Гутарка не існуе';
$string['errormessagetoolong'] = 'Паведамленьня даўжэйшае за максімальна даступнае.';
$string['errortranslatingdefault'] = 'Памылка перадачы стандартных наладаў ад плагіна, заміж іх выкарыстоўваюцца стандартныя сістэмныя налады.';
$string['eventgroupmessagesent'] = 'Групавое паведамленьне адпраўлена';
$string['eventmessagecontactadded'] = 'Кантакт паведамленьня даданы';
$string['eventmessagecontactremoved'] = 'Кантакт паведамленьня выдалены';
$string['eventmessagedeleted'] = 'Паведамленьне выдалена';
$string['eventmessagesent'] = 'Паведамленьне адпраўлена';
$string['eventmessageuserblocked'] = 'Карыстальнік заблакаваны';
$string['eventmessageuserunblocked'] = 'Карыстальнік адблакаваны';
$string['eventmessageviewed'] = 'Паведамленьне прагледжана';
$string['eventnotificationsent'] = 'Абвестка адпраўлена';
$string['eventnotificationviewed'] = 'Абвестка прагледжана';
$string['forced'] = 'Заблакавана';
$string['forcedmessage'] = 'Блакаваньне ўключана';
$string['groupconversations'] = 'Група';
$string['groupinfo'] = 'Інфа групы';
$string['guestnoeditmessage'] = 'Госьць-карыстальнік ня можа рэдагаваць налады паведамленьняў';
$string['guestnoeditmessageother'] = 'Госьць-карыстальнік ня можа рэдагаваць налады паведамленьняў іншых карыстальнікаў';
$string['hidemessagewindow'] = 'Схаваць вакно паведамленьняў';
$string['hidenotificationwindow'] = 'Схаваць вакно абвестак';
$string['individualconversations'] = 'Прыватная';
$string['info'] = 'Інфа карыстальніка';
$string['isnotinyourcontacts'] = '{$a} ня з\'яўляецца вашым кантактам.';
$string['loadmore'] = 'Загрузіць болей';
$string['loggedin'] = 'Анлайн';
$string['loggedin_help'] = 'Наладзьце як жадаеце атрымліваць абвесткі падчас уваходу ў Moodle';
$string['loggedindescription'] = 'Калі вы ўвайшлі ў Moodle';
$string['loggedoff'] = 'Афлайн';
$string['loggedoff_help'] = 'Наладзьце як жадаеце атрымліваць абвесткі, калі вы не ўвайшлі ў Moodle';
$string['loggedoffdescription'] = 'Калі вы не ўвайшлі ў Moodle';
$string['managemessageoutputs'] = 'Стандартныя перавагі абвестак';
$string['message'] = 'Паведамленьне';
$string['messagecontactrequest'] = '{$a->user} даслаў запыт на даданьне да кантактаў. Наведайце старонку вашых <a href="{$a->url}">запытаў на кантакт</a>, каб адказаць на запыт';
$string['messagecontactrequestsnotification'] = '{$a} даслаў запыт на даданьне ў якасьці кантакта.';
$string['messagecontactrequestsnotificationsubject'] = 'Запыт на кантакт ад {$a}';
$string['messagecontactrequestsubject'] = '{$a->sitename}: Запыт на кантакт ад {$a->user}';
$string['messagecontentaudio'] = 'Аўдыё';
$string['messagecontentimage'] = 'Выява';
$string['messagecontentmultimediageneral'] = 'Іншыя медыя';
$string['messagecontentvideo'] = 'Відэа';
$string['messagedrawerviewcontact'] = 'Дэталі карыстальніка {$a}';
$string['messagedrawerviewcontacts'] = 'Кантакты паведамленьня';
$string['messagedrawerviewconversation'] = 'Гутарка з {$a}';
$string['messagedrawerviewgroupinfo'] = 'Дэталі групы {$a}';
$string['messagedrawerviewoverview'] = 'Агляд паведамленьняў';
$string['messagedrawerviewsearch'] = 'Вынікі пошуку паведамленьняў для {$a}';
$string['messagedrawerviewsettings'] = 'Налады паведамленьняў';
$string['messageoutputs'] = 'Плагіны абвестак';
$string['messagepreferences'] = 'Перавагі паведамленьняў';
$string['messages'] = 'Паведамленьні';
$string['messagesselected:'] = 'Абраныя паведамленьні:';
$string['messagetextrequired'] = 'Калі ласка, надрукуйце тэкст паведамленьня';
$string['messagingdatahasnotbeenmigrated'] = 'Вашыя паведамленьні часова недасяжныя з-за абнаўленьня інфраструктуры паведамленьняў. Калі ласка, пачакайце іхняга пераносу (міграцыі).';
$string['muteconversation'] = 'Заглушыць';
$string['mutedconversation'] = 'Заглушаныя гутаркі';
$string['newmessage'] = 'Новае паведамленьне';
$string['newmessagesearch'] = 'Абярыце ці адшукайце кантакт, каб адправіць новае паведамленьне.';
$string['newonlymsg'] = 'Паказваць толькі новае';
$string['nocontactrequests'] = 'Запыты на даданьне ў кантакты адсутнічаюць';
$string['nocontacts'] = 'Кантакты адсутнічаюць';
$string['nocontactsgetstarted'] = 'Кантакты адсутнічаюць';
$string['nofavourites'] = 'Упадабаныя гутаркі адсутнічаюць';
$string['noframesjs'] = 'Выкарыстаць больш утульны інтэрфейс';
$string['nogroupconversations'] = 'Групавыя гутаркі адсутнічаюць';
$string['noindividualconversations'] = 'Прыватныя гутаркі адсутнічаюць';
$string['nomessagesfound'] = 'Паведамленьні ня знойдзены';
$string['noncontacts'] = 'Не кантакты';
$string['nonotifications'] = 'Вы ня маеце абвестак';
$string['noparticipants'] = 'Удзельнікі адсутнічаюць';
$string['noreply'] = 'Не адказвайце на гэтае паведамленьне';
$string['notificationdatahasnotbeenmigrated'] = 'Вашыя абвесткі часова недаступныя з-за абнаўленьня інфраструктуры абвестак. Калі ласка, пачакайце іх пераносу (міграцыі).';
$string['notificationimage'] = 'Выява абвесткі';
$string['notificationpreferences'] = 'Перавагі абвестак';
$string['notifications'] = 'Абвесткі';
$string['notificationwindow'] = 'Вакно абвестак';
$string['notincontacts'] = 'Вы мусіце дадаць {$a} да сваіх кантактаў, каб мець магчымасьць адпраўленьня паведамленьняў.';
$string['notincontactsheading'] = '{$a} адсутнічае ў вашых кантактых';
$string['numparticipants'] = '{$a} удзельніка(ў)';
$string['off'] = 'Выключана';
$string['offline'] = 'Афлайн';
$string['on'] = 'Уключана';
$string['online'] = 'Анлайн';
$string['otherparticipants'] = 'Іншыя ўдзельнікі';
$string['outputnotavailable'] = 'Не даступныя';
$string['page-message-x'] = 'Усе старонкі паведамленьняў';
$string['participants'] = 'Удзельнікі';
$string['pendingcontactrequests'] = 'Існуе {$a} запытаў на кантакт чакаючых адказу';
$string['permitted'] = 'Дазволена';
$string['privacy'] = 'Прыватнасьць';
$string['privacy:export:conversationprefix'] = 'Гутарка:';
$string['privacy:metadata:core_favourites'] = 'Упадабаныя карыстальнікам гутаркі';
$string['privacy:metadata:message_contact_requests'] = 'Сьпіс запытаў на кантакт';
$string['privacy:metadata:message_contact_requests:requesteduserid'] = 'ID карыстальніка, што атрымаў запыт на кантакт';
$string['privacy:metadata:message_contact_requests:timecreated'] = 'Час стварэньня запыта на кантакт';
$string['privacy:metadata:message_contact_requests:userid'] = 'ID карыстальніка, што адправіў запыт на кантакт';
$string['privacy:metadata:message_contacts'] = 'Сьпіс кантактаў';
$string['privacy:metadata:message_contacts:contactid'] = 'ID карыстальніка, што з\'яўляецца кантактам';
$string['privacy:metadata:message_contacts:timecreated'] = 'Час стварэньня кантакта';
$string['privacy:metadata:message_contacts:userid'] = 'ID карыстальніка, чый сьпіс кантактаў праглядаецца';
$string['privacy:metadata:message_conversation_actions'] = 'Сьпіс дзеяньняў карыстальніка падчас гутаркі';
$string['privacy:metadata:message_conversation_actions:action'] = 'Дзеяньне, якое было выканана';
$string['privacy:metadata:message_conversation_actions:conversationid'] = 'ID гутаркі, да якой належыць гэтае дзеяньне';
$string['privacy:metadata:message_conversation_actions:timecreated'] = 'Час стварэньня дзеяньня';
$string['privacy:metadata:message_conversation_actions:userid'] = 'ID карыстальніка, што выканаў гэтае дзеяньне';
$string['privacy:metadata:message_conversation_members'] = 'Сьпіс карыстальнікаў гутаркі';
$string['privacy:metadata:message_conversation_members:conversationid'] = 'ID гутаркі';
$string['privacy:metadata:message_conversation_members:timecreated'] = 'Час стварэньня чальца';
$string['privacy:metadata:message_conversation_members:userid'] = 'ID карыстальніка гутаркі';
$string['privacy:metadata:message_user_actions'] = 'Сьпіс дзеяньняў карыстальніка паведамленьня';
$string['privacy:metadata:message_user_actions:action'] = 'Дзеяньне, што было выканана';
$string['privacy:metadata:message_user_actions:messageid'] = 'ID паведамленьня, якому належыць гэтае дзеяньне';
$string['privacy:metadata:message_user_actions:timecreated'] = 'The time when the action was created';
$string['privacy:metadata:message_user_actions:userid'] = 'The ID of the user who performed this action';
$string['privacy:metadata:message_users_blocked'] = 'The list of blocked users';
$string['privacy:metadata:message_users_blocked:blockeduserid'] = 'The ID of the user who was blocked';
$string['privacy:metadata:message_users_blocked:timecreated'] = 'The time when the blocked action was created';
$string['privacy:metadata:message_users_blocked:userid'] = 'The ID of the user who performed the blocked action';
$string['privacy:metadata:messages'] = 'Messages';
$string['privacy:metadata:messages:conversationid'] = 'The ID of the conversation';
$string['privacy:metadata:messages:customdata'] = 'Custom data, usually containing internal IDs and a public URL of the sender image (user or group)';
$string['privacy:metadata:messages:fullmessage'] = 'The full message';
$string['privacy:metadata:messages:fullmessageformat'] = 'The format of the full message';
$string['privacy:metadata:messages:fullmessagehtml'] = 'The HTML format of the full message';
$string['privacy:metadata:messages:smallmessage'] = 'A small version of the message';
$string['privacy:metadata:messages:subject'] = 'The subject of the message';
$string['privacy:metadata:messages:timecreated'] = 'The time when the message was created';
$string['privacy:metadata:messages:useridfrom'] = 'The ID of the user who sent the message';
$string['privacy:metadata:notifications'] = 'Notifications';
$string['privacy:metadata:notifications:component'] = 'The component responsible for sending the notification';
$string['privacy:metadata:notifications:contexturl'] = 'The URL related to this notification';
$string['privacy:metadata:notifications:contexturlname'] = 'The name of the context';
$string['privacy:metadata:notifications:customdata'] = 'Custom data, usually containing internal IDs and a public URL of the sender picture (if any)';
$string['privacy:metadata:notifications:eventtype'] = 'The event type';
$string['privacy:metadata:notifications:fullmessage'] = 'The full notification';
$string['privacy:metadata:notifications:fullmessageformat'] = 'The notification format';
$string['privacy:metadata:notifications:fullmessagehtml'] = 'The HTML of the notification';
$string['privacy:metadata:notifications:smallmessage'] = 'The small message of the notification';
$string['privacy:metadata:notifications:subject'] = 'The subject of the notification';
$string['privacy:metadata:notifications:timecreated'] = 'The time when the notification was created';
$string['privacy:metadata:notifications:timeread'] = 'The time when the notification was read';
$string['privacy:metadata:notifications:useridfrom'] = 'The ID of the user who sent the notification';
$string['privacy:metadata:notifications:useridto'] = 'The ID of the user who received the notification';
$string['privacy:metadata:preference:core_message_settings'] = 'Settings related to messaging';
$string['privacy:request:preference:set'] = 'The value of the setting \'{$a->name}\' was \'{$a->value}\'';
$string['privacy_desc'] = 'You can restrict who can message you';
$string['processorsettings'] = 'Processor settings';
$string['providerenabled'] = 'Sending "{$a}" enabled status';
$string['providerprocesorisdisallowed'] = '"{$a->provider}" on "{$a->processor}" is locked off';
$string['providerprocesorislocked'] = '"{$a->provider}" on "{$a->processor}" is locked on';
$string['removecontact'] = 'Remove contact';
$string['removecontactconfirm'] = 'Are you sure you want to remove {$a} from your contacts?';
$string['removecoursefilter'] = 'Remove filter for course {$a}';
$string['removefromfavourites'] = 'Unstar conversation';
$string['removefromyourcontacts'] = 'Remove from contacts';
$string['requirecontacttomessage'] = 'You need to request {$a} to add you as a contact to be able to message them.';
$string['requiresconfiguration'] = 'Requires configuration';
$string['searchcombined'] = 'Search people and messages';
$string['searchforuser'] = 'Search for a user';
$string['searchforuserorcourse'] = 'Search for a user or course';
$string['searchmessages'] = 'Search messages';
$string['seeall'] = 'See all';
$string['selectmessagestodelete'] = 'Select messages to delete';
$string['selectnotificationtoview'] = 'Select from the list of notifications on the side to view more details';
$string['selfconversation'] = 'Personal space';
$string['selfconversationdefaultmessage'] = 'Save draft messages, links, notes etc. to access later.';
$string['send'] = 'Send';
$string['sendbulkmessage'] = 'Send message to {$a} people';
$string['sendbulkmessagesent'] = 'Message sent to {$a} people';
$string['sendbulkmessagesentsingle'] = 'Message sent to 1 person';
$string['sendbulkmessagesingle'] = 'Send message to 1 person';
$string['sendcontactrequest'] = 'Send contact request';
$string['sender'] = '{$a}:';
$string['sendingvia'] = 'Sending "{$a->provider}" via "{$a->processor}"';
$string['sendingviaenabled'] = 'Sending "{$a->provider}" via "{$a->processor}" enabled status';
$string['sendingvialocked'] = 'Sending "{$a->provider}" via "{$a->processor}" locked status';
$string['sendingviawhen'] = 'Sending "{$a->provider}" via "{$a->processor}" when {$a->state}';
$string['sendmessage'] = 'Send message';
$string['sendmessageto'] = 'Send message to {$a}';
$string['sendmessagetopopup'] = 'Send message to {$a} - new window';
$string['settings'] = 'Settings';
$string['showmessagewindownonew'] = 'Show message window with no new messages';
$string['showmessagewindowwithcount'] = 'Show message window with {$a} new messages';
$string['shownotificationwindownonew'] = 'Show notification window with no new notifications';
$string['shownotificationwindowwithcount'] = 'Show notification window with {$a} new notifications';
$string['togglemessagemenu'] = 'Toggle messaging drawer';
$string['togglenotificationmenu'] = 'Toggle notifications menu';
$string['totalconversations'] = '{$a} total conversations';
$string['touserdoesntexist'] = 'You cannot send a message to a user ID ({$a}) that doesn\'t exist.';
$string['unabletomessage'] = 'You are unable to message this user';
$string['unblock'] = 'Unblock';
$string['unblockcontact'] = 'Unblock contact';
$string['unblockuser'] = 'Unblock user';
$string['unblockuserconfirm'] = 'Are you sure you want to unblock {$a}?';
$string['unknownuser'] = 'Unknown user';
$string['unmuteconversation'] = 'Unmute';
$string['unreadconversations'] = 'There are {$a} unread conversations';
$string['unreadmessages'] = 'There are {$a} unread messages';
$string['unreadnewgroupconversationmessage'] = 'New message from {$a->name} in {$a->conversationname}';
$string['unreadnewmessage'] = 'New message from {$a}';
$string['unreadnotification'] = 'Unread notification: {$a}';
$string['unreadnotifications'] = 'There are {$a} unread notifications';
$string['useentertosend'] = 'Use enter to send';
$string['usercantbemessaged'] = 'You can\'t message {$a} due to their message preferences. Try adding them as a contact.';
$string['userwouldliketocontactyou'] = '{$a} would like to contact you';
$string['viewfullnotification'] = 'View full notification';
$string['viewmessageswith'] = 'View messages with {$a}';
$string['viewnotificationresource'] = 'Go to: {$a}';
$string['viewunreadmessageswith'] = 'View unread messages with {$a}';
$string['wouldliketocontactyou'] = 'Would like to contact you';
$string['writeamessage'] = 'Write a message...';
$string['you'] = 'You:';
$string['youhaveblockeduser'] = 'You have blocked this user.';
$string['yourcontactrequestpending'] = 'Your contact request is pending with {$a}';
