<?php
// This file is part of Moodle - https://moodle.org/
//
// Moodle is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// Moodle is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with Moodle.  If not, see <https://www.gnu.org/licenses/>.

/**
 * Strings for component 'workshop', language 'en', version '4.0'.
 *
 * @package     workshop
 * @category    string
 * @copyright   1999 Martin Dougiamas and contributors
 * @license     https://www.gnu.org/copyleft/gpl.html GNU GPL v3 or later
 */

defined('MOODLE_INTERNAL') || die();

$string['activitydate:assessmentsclose'] = 'Ацэньваньні закрываюцца:';
$string['activitydate:assessmentsclosed'] = 'Ацэньваньні закрыты:';
$string['activitydate:assessmentsopen'] = 'Ацэньваньні адкрываюцца:';
$string['activitydate:assessmentsopened'] = 'Ацэньваньні адкрыты:';
$string['activitydate:submissionsclose'] = 'Адпраўленьні закрываюцца:';
$string['activitydate:submissionsclosed'] = 'Адпраўленьні закрыты:';
$string['activitydate:submissionsopen'] = 'Адпраўленьні адкрываюцца:';
$string['activitydate:submissionsopened'] = 'Адпраўленьні адкрыты:';
$string['aggregategrades'] = 'Пераразьлічыць адзнакі';
$string['aggregation'] = 'Агрэгацыя ацэнак';
$string['allocate'] = 'Прызначыць адпраўленьні';
$string['allocatedetails'] = 'чакана: {$a->expected}<br />адпраўлена: {$a->submitted}<br />прызначана: {$a->allocate}';
$string['allocation'] = 'Прызначэньне адпраўленьняў';
$string['allocationconfigured'] = 'Прызначэньне сканфігуравана';
$string['allocationdone'] = 'Прызначэньне зроблена';
$string['allocationerror'] = 'Памылка прызначэньня';
$string['allowedfiletypesforoverallfeedback'] = 'Дазволеныя тыпы файлаў для ўкладаньняў водгукаў';
$string['allowedfiletypesforoverallfeedback_help'] = 'Тыпы файлаў для ўкладаньняў водгукаў льга абмежаваць вызначаным сьпісам дазволеных файлаў. Калі поле пакінуць пустым, тады ўсе тыпы файлаў будуць дазволены.';
$string['allowedfiletypesforoverallfeedback_link'] = 'admin/tool/filetypes/index';
$string['allowedfiletypesforsubmission'] = 'Дазволеныя тыпы файлаў для ўкладаньняў адпраўленьняў';
$string['allowedfiletypesforsubmission_help'] = 'Тыпы файлаў для ўкладаньняў адпраўленьняў льга абмежаваць вызначаным сьпісам дазволеных файлаў. Калі поле пакінуць пустым, тады ўсе тыпы файлаў будуць дазволены.';
$string['allowedfiletypesforsubmission_link'] = 'admin/tool/filetypes/index';
$string['allsubmissions'] = 'Усе адпраўленьні ({$a})';
$string['alreadygraded'] = 'Ужо ацэнена';
$string['areaconclusion'] = 'Тэкст высновы';
$string['areainstructauthors'] = 'Інструкцыі для адпраўленьня';
$string['areainstructreviewers'] = 'Інструкцыі для ацэньваньня';
$string['areaoverallfeedbackattachment'] = 'Выніковыя ўкладаньні водгукаў';
$string['areaoverallfeedbackcontent'] = 'Выніковыя тэксты водгукаў';
$string['areasubmissionattachment'] = 'Укладаньні адпраўленьня';
$string['areasubmissioncontent'] = 'Тэксты адпраўленьня';
$string['assess'] = 'Ацаніць';
$string['assessedexample'] = 'Ацэненае прыкладнае адпраўленьне';
$string['assessedsubmission'] = 'Ацэненае адпраўленьне';
$string['assessingexample'] = 'Ацэньваньне прыкладнага адпраўленьня';
$string['assessingsubmission'] = 'Ацэньваньне адпраўленьня';
$string['assessment'] = 'Ацэньваньне';
$string['assessmentby'] = 'ацаніў(ла) <a href="{$a->url}">{$a->name}</a>';
$string['assessmentbyfullname'] = 'Ацаніў(ла) {$a}';
$string['assessmentbyyourself'] = 'Вашае ацэньваньне';
$string['assessmentdeleted'] = 'Ацэньваньне адмацавана';
$string['assessmentend'] = 'Апошні тэрмін ацэньваньня';
$string['assessmentendbeforestart'] = 'Апошні тэрмін ацэньваньня ня можа быць усталяваным ранейшым за дату адкрыцьця ацэньваньня';
$string['assessmentenddatetime'] = 'Апошні тэрмін ацэньваньня: {$a->daydatetime} ({$a->distanceday})';
$string['assessmentendevent'] = 'Апошні тэрмін ацэньваньня {$a}';
$string['assessmentform'] = 'Форма ацэньваньня';
$string['assessmentofsubmission'] = '<a href="{$a->assessmenturl}">Ацэньваньне</a> <a href="{$a->submissionurl}">{$a->submissiontitle}</a>';
$string['assessmentreference'] = 'Эталоннае ацэньваньне';
$string['assessmentreferenceconflict'] = 'Нельга ацаніць прыкладнае адпраўленьне, дзеля якога вы падалі эталоннае ацэньваньне.';
$string['assessmentreferenceneeded'] = 'Вы ацанілі гэтае прыкладнае адпраўленьне, каб падаць эталоннае ацэньваньне. Націсьніце кнопку \'Працягнуць\', каб ацаніць адпраўленьне.';
$string['assessments'] = 'Ацэньваньні';
$string['assessmentsettings'] = 'Налады ацэньваньня';
$string['assessmentstart'] = 'Адкрыцьцё ацэньваньня з';
$string['assessmentstartdatetime'] = 'Адкрыцьцё ацэньваньня з {$a->daydatetime} ({$a->distanceday})';
$string['assessmentstartevent'] = 'Ацэньваньне адкрываецца {$a}';
$string['assessmentweight'] = 'Вага ацэньваньня';
$string['assignedassessments'] = 'Прызначаныя адпраўленьні дзеля ацэньваньня';
$string['assignedassessmentsnone'] = 'Вы ня маеце прызначаных адпраўленьняў на ацэньваньне';
$string['backtoeditform'] = 'Назад да рэдагаваньня формы';
$string['byfullname'] = '<a href="{$a->url}">{$a->name}</a>';
$string['byfullnamewithoutlink'] = '{$a}';
$string['calculategradinggrades'] = 'Разьлічыць адзнакі ацэньваньняў';
$string['calculategradinggradesdetails'] = 'чакана: {$a->expected}<br />разьлічана: {$a->calculated}';
$string['calculatesubmissiongrades'] = 'Разьлічыць адзнакі адпраўленьняў';
$string['calculatesubmissiongradesdetails'] = 'чакана: {$a->expected}<br />разьлічана: {$a->calculated}';
$string['chooseuser'] = 'Абраць карыстальніка...';
$string['clearaggregatedgrades'] = 'Ачысьціць усе агрэганаваныя адзнакі';
$string['clearaggregatedgrades_help'] = 'Агрэганаваныя адзнакі за адпраўленьні і ацэньваньні будуць скінуты. Вы можаце пераразьлічыць гэтыя адзнакі з нуля на этапе ацэньваньня.';
$string['clearaggregatedgradesconfirm'] = 'Вы ўпэўнены, што жадаеце ачысьціць разьлічаныя адзнакі за адпраўленьні і ацэньваньні?';
$string['clearassessments'] = 'Ачысьціць ацэньваньні';
$string['clearassessments_help'] = 'Разьлічаныя адзнакі за адпраўленьні і ацэньваньні будуць скінуты. Інфармацыя пра тое, як былі запоўнены формы ацэньваньня, дагэтуль захоўваецца, але ўсе рэцэнзенты мусяць наноў адкрыць форму ацэньваньня і перазахаваць яе, каб зноў атрымаць разьлічаныя адзнакі.';
$string['clearassessmentsconfirm'] = 'Вы ўпэўнены, што жадаеце ацысьціць усе адзнакі ацэньваньня? Вы ня зможаце вярнуць інфармацыю самастойна, рэцэнзенты будуць вымушаны ацаніць прызначаныя адпраўленьні наноў.';
$string['conclusion'] = 'Выснова';
$string['conclusion_help'] = 'Тэкст высновы паказваецца ўдзельнікам напрыканцы актыўнасьці.';
$string['configexamplesmode'] = 'Стандартны рэжым прыкладных ацэньваньняў у майстэрнях';
$string['configgrade'] = 'Стандартная максімальная адзнака для адпраўленьняў у майстэрнях';
$string['configgradedecimals'] = 'Стандартная колькасьць лічбаў, якая мусіць адлюстроўвацца пасьля дзесятковай кропкі падчас адлюстраваньня адзнак.';
$string['configgradinggrade'] = 'Стандартная максімальная адзнака для ацэньваньняў у майстэрнях';
$string['configmaxbytes'] = 'Стандартны максімальны памер файлаў адпраўленьняў дзеля ўсіх майстэрняў на сайце (з улікам абмежаваньняў курса і іншых лакальных наладаў)';
$string['configstrategy'] = 'Стандартная стратэгія ацэньваньня ў майстэрнях';
$string['createsubmission'] = 'Дадаць адпраўленьне';
$string['crontask'] = 'Фонавая апрацоўка модуля майстэрня';
$string['daysago'] = '{$a} дзён таму';
$string['daysleft'] = '{$a} дзён засталося';
$string['daystoday'] = 'сёньня';
$string['daystomorrow'] = 'заўтра';
$string['daysyesterday'] = 'учора';
$string['deadlinesignored'] = 'Часовыя абмежаваньні на вас не распаўсюджваюцца';
$string['deletesubmission'] = 'Выдаліць адпраўленьне';
$string['editassessmentform'] = 'Рэдагаваць форму ацэньваньня';
$string['editassessmentformstrategy'] = 'Рэдагаваць форму ацэньваньня ({$a})';
$string['editingassessmentform'] = 'Рэдагаваньне формы ацэньваньня';
$string['editingsubmission'] = 'Рэдагаваньне адпраўленьня';
$string['editsubmission'] = 'Рэдагаваць адпраўленьне';
$string['err_multiplesubmissions'] = 'Падчас рэдагаваньня гэтай формы, іншая версія адпраўленьня была захавана. Шматразовыя адпраўленьні адным карыстальнікам забаронены.';
$string['err_removegrademappings'] = 'Нельга выдаліць нявыкарыстаныя параўнаньні адзнак';
$string['evaluategradeswait'] = 'Калі ласка, пачакайце, пакуль адзнакі будуць ацэнены і разьлічаны';
$string['evaluation'] = 'Ацэньваньне адзнак';
$string['evaluationmethod'] = 'Метад ацэньваньня адзнак';
$string['evaluationmethod_help'] = 'Метад ацэньваньня адзнак вызначае, як будуць разьлічвацца адзнакі ацэньваньняў. Вы можаце дазволіць яму неаднаразова пераразьлічваць адзнакі з рознымі наладамі, пакуль вас не задаволіць вынік.';
$string['evaluationsettings'] = 'Налады ацэньваньня адзнак';
$string['eventassessableuploaded'] = 'Адпраўленьне было запампована.';
$string['eventassessmentevaluated'] = 'Ацэньваньне ацэнена';
$string['eventassessmentevaluationsreset'] = 'Ацэньваньне ацэньваньня скінута';
$string['eventassessmentreevaluated'] = 'Ацэньваньне пераацэнена';
$string['eventphaseautomaticallyswitched'] = 'Этап аўтаматычна пераключаны';
$string['eventphaseswitched'] = 'Этап пераключаны';
$string['eventsubmissionassessed'] = 'Адпраўленьне ацэнена';
$string['eventsubmissionassessmentsreset'] = 'Ацэньваньне адпраўленьня ачышчана';
$string['eventsubmissioncreated'] = 'Адпраўленьне створана';
$string['eventsubmissiondeleted'] = 'Адпраўленьне выдалена';
$string['eventsubmissionreassessed'] = 'Адпраўленьне пераацэнена';
$string['eventsubmissionupdated'] = 'Адпраўленьне абноўлена';
$string['eventsubmissionviewed'] = 'Адпраўленьне прагледжана';
$string['example'] = 'Прыкладнае адпраўленьне';
$string['exampleadd'] = 'Дадаць прыкладнае адпраўленьне';
$string['exampleassess'] = 'Ацаніць прыкладнае адпраўленьне';
$string['exampleassessments'] = 'Прыкладныя адпраўленьні дзеля ацэньваньня';
$string['exampleassesstask'] = 'Ацаніць прыклады';
$string['exampleassesstaskdetails'] = 'чакана: {$a->expected}<br />ацэнена: {$a->assessed}';
$string['examplecomparing'] = 'Параўнаньне ацэньваньняў прыкладнага адпраўленьня';
$string['exampledelete'] = 'Выдаліць прыклад';
$string['exampledeleteconfirm'] = 'Вы ўпэўнены, што жадаеце выдаліць наступнае прыкладнае адпраўленьне? Націсьніце кнопку \'Працягнуць\', каб выдаліць адпраўленьне.';
$string['exampleedit'] = 'Рэдагаваць прыклад';
$string['exampleediting'] = 'Рэдагаваньне прыкладу';
$string['exampleneedassessed'] = 'Спачатку вы мусіце ацаніць усе прыкладныя адпраўленьні';
$string['exampleneedsubmission'] = 'Спачатку вы мусіце адправіць сваю працу і ацаніць усе прыкладныя адпраўленьні';
$string['examplesbeforeassessment'] = 'Прыклады даступныя пасьля вашага адпраўленьня і мусяць быць ацэнены да калегійнага ацэньваньня';
$string['examplesbeforesubmission'] = 'Прыклады мусяць быць ацэнены да вашага адпраўленьня';
$string['examplesmode'] = 'Рэжым ацэньваньня прыкладаў';
$string['examplesubmissions'] = 'Прыкладныя адпраўленьні';
$string['examplesvoluntary'] = 'Ацэньваньне прыкладных адпраўленьняў самаахвотнае';
$string['exportsubmission'] = 'Экспартаваць гэтую старонку';
$string['feedbackauthor'] = 'Водгук дзеля аўтара';
$string['feedbackauthorattachment'] = 'Укладаньне';
$string['feedbackby'] = 'Водгук ад {$a}';
$string['feedbackreviewer'] = 'Водгук для рэцэнзента';
$string['feedbacksettings'] = 'Водгук';
$string['formataggregatedgrade'] = '{$a->grade}';
$string['formataggregatedgradeover'] = '<del>{$a->grade}</del><br /><ins>{$a->over}</ins>';
$string['formatpeergrade'] = '<span class="grade">{$a->grade}</span> <span class="gradinggrade">({$a->gradinggrade})</span>';
$string['formatpeergradeover'] = '<span class="grade">{$a->grade}</span> <span class="gradinggrade">(<del>{$a->gradinggrade}</del> / <ins>{$a->gradinggradeover}</ins>)</span>';
$string['formatpeergradeoverweighted'] = '<span class="grade">{$a->grade}</span> <span class="gradinggrade">(<del>{$a->gradinggrade}</del> / <ins>{$a->gradinggradeover}</ins>)</span> @ <span class="weight">{$a->weight}</span>';
$string['formatpeergradeweighted'] = '<span class="grade">{$a->grade}</span> <span class="gradinggrade">({$a->gradinggrade})</span> @ <span class="weight">{$a->weight}</span>';
$string['givengrades'] = 'Выстаўленыя адзнакі';
$string['grade_grading_name'] = 'Ацэньваньне';
$string['grade_submission_name'] = 'Адпраўленьне';
$string['gradecalculated'] = 'Разьлічаная адзнака для адпраўленьня';
$string['gradedecimals'] = 'Дзясяткавыя знакі ў адзнаках';
$string['gradegivento'] = '&gt;';
$string['gradeinfo'] = 'Адзнака: {$a->received} з {$a->max}';
$string['gradeitemassessment'] = '{$a->workshopname} (assessment)';
$string['gradeitemsubmission'] = '{$a->workshopname} (submission)';
$string['gradeover'] = 'Перавызначыць адзнаку для адпраўленьня';
$string['gradereceivedfrom'] = '&lt;';
$string['gradesreport'] = 'Справаздача пра адзнакі майстэрні';
$string['gradetopassgrading'] = 'Прахадная адзнака ацэньваньня';
$string['gradetopasssubmission'] = 'Прахадная адзнака адпраўленьня';
$string['gradinggrade'] = 'Адзнака для ацэньваньня';
$string['gradinggrade_help'] = 'Гэтая налада вызначае максімальную адзнаку, якую льга атрымаць за ацэньваньне адпраўленьня.';
$string['gradinggradecalculated'] = 'Разьлічаная адзнака за ацэньваньне';
$string['gradinggradeof'] = 'Адзнака за ацэньваньне (з {$a})';
$string['gradinggradeover'] = 'Перавызначыць адзнаку за ацэньваньне';
$string['gradingsettings'] = 'Налады ацэньваньня';
$string['groupnoallowed'] = 'Вам забаронены доступ ува ўсякую групу ў гэтай майстэрні';
$string['iamsure'] = 'Так, я ўпэўнены(а)';
$string['indicator:cognitivedepth'] = 'Пазнаваньне майстэрні';
$string['indicator:cognitivedepth_help'] = 'Гэты паказьнік заснаваны на глыбіні пазнаваньня, якую дасягнуў студэнт у актыўнасьці-Майстэрні.';
$string['indicator:cognitivedepthdef'] = 'Пазнаваньне майстэрні';
$string['indicator:cognitivedepthdef_help'] = 'Удзельнік дасягную гэтага адсотку пазнавальнага ўцягненьня, прапанаваны актыўнасьцямі-майстэрнямі ў аналізаваны тэрмін (Роўні = Без прагляду, Прагляд, Адпраўка, Прагляд водгуку, Каментар водгуку, Паўторнае адпраўленьне пасьля прагляду водгуку)';
$string['indicator:cognitivedepthdef_link'] = 'Learning_analytics_indicators#Cognitive_depth';
$string['indicator:socialbreadth'] = 'Сацыяльнасьць майстэрні';
$string['indicator:socialbreadth_help'] = 'Гэты паказьнік згрунтаваны на сацыяльнай шырыні, якую дасягнуў студэнт ў актыўнасьці-майстэрне.';
$string['indicator:socialbreadthdef'] = 'Сацыяльнасьць майстэрні';
$string['indicator:socialbreadthdef_help'] = 'Удзельнік дасягную гэтага адсотку сацыяльнай шырыні, прапанаванай актыўнасьцямі-майстэрнямі ў аналізаваны тэрмін (Роўні = Адсутнасьць удзелу, Самотны удзел, Сумесны ўдзел)';
$string['indicator:socialbreadthdef_link'] = 'Learning_analytics_indicators#Social_breadth';
$string['info'] = 'Інфа';
$string['instructauthors'] = 'Інструкцыі для адпраўленьня';
$string['instructreviewers'] = 'Інструкцыі для ацэньваньня';
$string['introduction'] = 'Апісваньне';
$string['latesubmissions'] = 'Позьнія адпраўленьні';
$string['latesubmissions_desc'] = 'Дазволіць адпраўленьні пасьля апошняга тэрміна ацэньваньня';
$string['latesubmissions_help'] = 'Калі ўключана, аўтары могуць адпраўляць свае працы пасьля сканчэньня апошняга тэрміна адпраўленьня ці падчас этапу ацэньваньня. Але позьнія адпраўленьні нельга рэдагаваць.';
$string['latesubmissionsallowed'] = 'Позьнія адпраўленьні дазволены';
$string['legacyallocationplugincron'] = 'Прызначэньне спадкаемнага cron майстэрні';
$string['maxbytes'] = 'Максімальны памер укладаньня адпраўленьня';
$string['modulename'] = 'Майстэрня';
$string['modulename_help'] = 'Модуль актыўнасьць-майстэрня дазваляе зьбіраць, рэцэнзаваць і калегіяльна ацэньваць студэнцкія працы.

Студэнты могуць адпраўляць любы лічбавы кантэнт (файлы), напрыклад, word-дакументы і excel-табліцы, а таксама друкаваць тэкст непасрэдна ў поле з дапамогай тэкставага рэдактара.

Адпраўленьні ацэньваюцца з дапамогай шматкратнай формы ацэньваньня, вызначанай настаўнікам. Працэс калегіяльнага ацэньваньня і разуменьня формы ацэньваньня льга адпрацаваць загадзя, з дапамогай прыкладных ацэньваньняў, паданых настаўнікам, ды эталоннага ацэньваньня. Студэнтам забясьпечваецца магчымасьць ацэньваньня аднога ці некалькіх адпраўленьняў ад іхніх калегаў. Адпраўленьні і рэцэнзіі могуць быць ананімнымі, калі спатрэбіцца.

Студэнты атрымліваюць дзьве адзнакі ўва актыўнасьці-майстэрні: адзнаку за сваё адпраўленьне і адзнаку за іхнія калегійныя ацэньваньні адпраўленьняў сваіх калегаў. Абедзьве адзнакі запісваюцца ў журнал адзнак.';
$string['modulename_link'] = 'mod/workshop/view';
$string['modulenameplural'] = 'Майстэрні';
$string['myassessments'] = 'Мае ацэньваньні';
$string['mysubmission'] = 'Маё адпраўленьне';
$string['nattachments'] = 'Максімальная колькасьць укладаньняў ува адпраўленьні';
$string['noexamples'] = 'У гэтай майстэрні дагэтуль няма прыкладаў';
$string['noexamplesformready'] = 'Вы мусіце вызначыць форму ацэньваньня, перш чым падаваць прыкладныя адпраўленьні';
$string['nogradeyet'] = 'Пакуль няма адзнакі';
$string['nosubmissionfound'] = 'Адпраўленьні для гэтага карыстальніка ня знойдзены';
$string['nosubmissions'] = 'У гэтай майстэрні пакуль няма адпраўленьняў';
$string['nosubmissiontype'] = 'Прынамсі адзін тып адпраўленьня мусіць быць даступны';
$string['notassessed'] = 'Пакуль не ацэнена';
$string['nothingfound'] = 'Няма чаго паказваць';
$string['nothingtoreview'] = 'Няма чаго рэцэнзаваць';
$string['notoverridden'] = 'Не перавызначана';
$string['noworkshops'] = 'У гэтым курсе няма майстэрняў';
$string['noyoursubmission'] = 'Вы дагэтуль не адправілі сваю працу';
$string['nullgrade'] = '-';
$string['overallfeedback'] = 'Выніковы водгук';
$string['overallfeedbackfiles'] = 'Максімальная колькасьць укладаньняў у выніковым водгуке';
$string['overallfeedbackmaxbytes'] = 'Максімальны памер укладаньня ў выніковым водгуке';
$string['overallfeedbackmode'] = 'Рэжым выніковага водгука';
$string['overallfeedbackmode_0'] = 'Адключаны';
$string['overallfeedbackmode_1'] = 'Уключаны і неабавязковы';
$string['overallfeedbackmode_2'] = 'Уключаны і абавязковы';
$string['overallfeedbackmode_help'] = 'Калі ўключана, у ніжняй частцы формы ацэньваньня адлюстроўваецца тэкставае поле. Рэцэнзенты могуць тут пакідаць выніковы водгук ацэньваньня ці падаваць дадатковыя тлумачэньні іхняга ацэньваньня.';
$string['page-mod-workshop-x'] = 'Усякая старонка модуля-майстэрні';
$string['participant'] = 'Удзельнік';
$string['participantrevierof'] = 'Удзельнік(ца) рэцэнзаваў(ла)';
$string['participantreviewedby'] = 'Удзельнік рэцэнзаваны';
$string['phaseassessment'] = 'Этап ацэньваньня';
$string['phaseclosed'] = 'Закрыта';
$string['phaseevaluation'] = 'Этап выстаўленьня адзнак';
$string['phasesetup'] = 'Усталёвачны этап';
$string['phasesoverlap'] = 'Этап адпраўленьня і этап ацэньваньня ня могуць супадаць';
$string['phasesubmission'] = 'Этап адпраўленьня';
$string['pluginadministration'] = 'Адміністраваньне майстэрні';
$string['pluginname'] = 'Майстэрня';
$string['prepareexamples'] = 'Падрыхтаваць прыкладныя адпраўленьні';
$string['previewassessmentform'] = 'Прадпрагляд';
$string['privacy:metadata:aggregatedgradinggrade'] = 'Агрэганаваная адзнака за ўсе ацэньваньні, зробленая карыстальнікам ў гэнай актыўнасьці-майстэрні';
$string['privacy:metadata:assessmentgrade'] = 'Агрэганаваная адзнака за адпраўленьне, прапанаваная гэтым ацэньваньнем';
$string['privacy:metadata:assessmentgradinggrade'] = 'Адзнака за гэтае ацэньваньне';
$string['privacy:metadata:assessmentgradinggradeover'] = 'Ручное перавызначэньне значэньня адзнакі за гэтае ацэньваньне';
$string['privacy:metadata:assessmentid'] = 'ID ацэньваньня';
$string['privacy:metadata:authorid'] = 'ID аўтара адпраўленьня';
$string['privacy:metadata:dimensiongrade'] = 'Адзнака ў паданым значэньні ацэньваньня';
$string['privacy:metadata:dimensionid'] = 'ID значэньня ацэньваньня';
$string['privacy:metadata:example'] = 'Ці рэпрэзентуе гэты запіс прыкладнае адпраўленьне';
$string['privacy:metadata:feedbackauthor'] = 'Водгук для аўтара';
$string['privacy:metadata:feedbackauthorformat'] = 'Тэкставы фармат водгука для аўтара';
$string['privacy:metadata:feedbackreviewer'] = 'Водгук для карыстальніка, што падаў ацэньваньне';
$string['privacy:metadata:feedbackreviewerformat'] = 'Тэкставы фармат водгука для карыстальніка, што падаў ацэньваньне';
$string['privacy:metadata:late'] = 'Ці было адпраўленьне адпраўлена пасьля апошняга тэрміна';
$string['privacy:metadata:peercomment'] = 'Каментар да адзнакі, якую выставіў карыстальнік, што падаў ацэньваньне';
$string['privacy:metadata:peercommentformat'] = 'Тэкставы фармат каментару, на выстаўленую адзнаку';
$string['privacy:metadata:preference:perpage'] = 'Колькасьць адпраўленьняў, якую карыстальнік жадае бачыць на адной старонцы';
$string['privacy:metadata:preference:viewlet-allexamples-collapsed'] = 'Згорнуты/разгорнуты стан вьюлета \'Прыкладныя адпраўленьні\'.';
$string['privacy:metadata:preference:viewlet-allsubmissions-collapsed'] = 'Згорнуты/разгорнуты стан вьюлета \'Справаздача па адпраўленьням майстэрні\'.';
$string['privacy:metadata:preference:viewlet-assessmentform-collapsed'] = 'Згорнуты/разгорнуты стан вьюлета \'Форма ацэньваньня\'.';
$string['privacy:metadata:preference:viewlet-assignedassessments-collapsed'] = 'Згорнуты/разгорнуты стан вьюлета \'Прызначаныя адпраўленьні дзеля ацэньваньня\'.';
$string['privacy:metadata:preference:viewlet-cleargrades-collapsed'] = 'Згорнуты/разгорнуты стан вьюлета \'Прылады майстэрні\'.';
$string['privacy:metadata:preference:viewlet-conclusion-collapsed'] = 'Згорнуты/разгорнуты стан вьюлета \'Выснова\'.';
$string['privacy:metadata:preference:viewlet-examples-collapsed'] = 'Згорнуты/разгорнуты стан вьюлета \'Прыкладныя адпраўленьні дзеля ацэньваньня\'.';
$string['privacy:metadata:preference:viewlet-examplesfail-collapsed'] = 'Згорнуты/разгорнуты стан вьюлета \'Прыкладныя адпраўленьні дзеля ацэньваньня\'.';
$string['privacy:metadata:preference:viewlet-gradereport-collapsed'] = 'Згорнуты/разгорнуты стан вьюлета \'Справаздача пра адзнакі майстэрні\'.';
$string['privacy:metadata:preference:viewlet-instructauthors-collapsed'] = 'Згорнуты/разгорнуты стан вьюлета \'Інструкцыі для адпраўленьня\'.';
$string['privacy:metadata:preference:viewlet-instructreviewers-collapsed'] = 'Згорнуты/разгорнуты стан вьюлета \'Інструкцыі для ацэньваньня\'.';
$string['privacy:metadata:preference:viewlet-intro-collapsed'] = 'Згорнуты/разгорнуты стан вьюлета \'Апісаньне\'.';
$string['privacy:metadata:preference:viewlet-overallfeedback-collapsed'] = 'Згорнуты/разгорнуты стан вьюлета \'Выніковы водгук\'.';
$string['privacy:metadata:preference:viewlet-ownsubmission-collapsed'] = 'Згорнуты/разгорнуты стан вьюлета \'Вашае адпраўленьне\'.';
$string['privacy:metadata:preference:viewlet-publicsubmissions-collapsed'] = 'Згорнуты/разгорнуты стан вьюлета \'Апублікаваныя адпраўленьні\'.';
$string['privacy:metadata:preference:viewlet-yourgrades-collapsed'] = 'Згорнуты/разгорнуты стан вьюлета \'Вашыя адзнакі\'.';
$string['privacy:metadata:published'] = 'Ці трэба адпраўленьні публікаваць усім удзельнікам пасьля закрыцьця майстэрні';
$string['privacy:metadata:reviewerid'] = 'ID карыстальніка, што падаў ацэньваньне';
$string['privacy:metadata:strategy'] = 'Назва падплагіна стратэгіі ацэньваньня, што інтэрпрэтуе значэньні запісаў';
$string['privacy:metadata:submissioncontent'] = 'Зьмесьціва адпраўленьня';
$string['privacy:metadata:submissioncontentformat'] = 'Тэкставы фармат зьмесьціва адпраўленьня';
$string['privacy:metadata:submissiongrade'] = 'Агрэгаваная адзнака за адпраўленьне, запісаная ў форме дзясяткавай лічбы зь інтэрвалу 0..100';
$string['privacy:metadata:submissiongradeover'] = 'Уручную перавызначанае значэньне агрэгаванай адзнакі';
$string['privacy:metadata:submissionid'] = 'ID адпраўленьня';
$string['privacy:metadata:submissiontitle'] = 'Назва адпраўленьня';
$string['privacy:metadata:subsystem:corefiles'] = 'Захаваньне ўбудаваных альбо ўкладзеных у тэкст адпраўленьня файлаў модуля-майстэрні';
$string['privacy:metadata:subsystem:coreplagiarism'] = 'Модуль-майстэрня мае ўбудаваную падтрымку сістэм антыплагіяту';
$string['privacy:metadata:timeaggregated'] = 'Час апошняга вылічэньня агрэгаванай адзнакі';
$string['privacy:metadata:timecreated'] = 'Час стварэньня гэтага запісу ў базе дадзеных';
$string['privacy:metadata:timemodified'] = 'Час апошняй зьмены гэтага запісу ў базе дадзеных';
$string['privacy:metadata:userid'] = 'ID карыстальніка, дзеля якога разьлічана агрэгаваная адзнака';
$string['privacy:metadata:weight'] = 'Вага ацэньваньня';
$string['privacy:metadata:workshopaggregations'] = 'Захоўвае агрэгаваныя адзнакі для ацэньваньня';
$string['privacy:metadata:workshopassessments'] = 'Захоўвае інфармацыю пра прызначэньне ацэньваньняў для адпраўленьняў модуля-майстэрні';
$string['privacy:metadata:workshopgrades'] = 'Захоўвае інфармацыю пра запаўненьне формаў ацэньваньня адзнакамі і каментарамі';
$string['privacy:metadata:workshopid'] = 'ID актыўнасьці-майстэрні';
$string['privacy:metadata:workshopsubmissions'] = 'Захоўвае інфармацыю пра адпраўленьні модуля-майстэрні';
$string['privacy:request:delete:content'] = 'Зьмесьціва было выдалена (па запыту карыстальніка ці з-за пратэрміноўкі)';
$string['privacy:request:delete:title'] = '[Выдалена]';
$string['publishedsubmissions'] = 'Апублікаваныя адпраўленьні';
$string['publishsubmission'] = 'Publish submission';
$string['publishsubmission_help'] = 'Published submissions are available to the others when the workshop is closed.';
$string['reassess'] = 'Re-assess';
$string['receivedgrades'] = 'Grades received';
$string['recentassessments'] = 'Workshop assessments:';
$string['recentsubmissions'] = 'Workshop submissions:';
$string['resetassessments'] = 'Delete all assessments';
$string['resetassessments_help'] = 'You can choose to delete just allocated assessments without affecting submissions. If submissions are to be deleted, their assessments will be deleted implicitly and this option is ignored. Note this also includes assessments of example submissions.';
$string['resetphase'] = 'Switch to the setup phase';
$string['resetphase_help'] = 'If enabled, all workshops will be put into the initial setup phase.';
$string['resetsubmissions'] = 'Delete all submissions';
$string['resetsubmissions_help'] = 'All the submissions and their assessments will be deleted. This does not affect example submissions.';
$string['saveandclose'] = 'Save and close';
$string['saveandcontinue'] = 'Save and continue editing';
$string['saveandpreview'] = 'Save and preview';
$string['saveandshownext'] = 'Save and show next';
$string['search:activity'] = 'Workshop - activity information';
$string['selfassessmentdisabled'] = 'Self-assessment disabled';
$string['showingperpage'] = 'Showing {$a} items per page';
$string['showingperpagechange'] = 'Change ...';
$string['someuserswosubmission'] = 'There is at least one author who has not yet submitted their work';
$string['sortasc'] = 'Ascending sort';
$string['sortdesc'] = 'Descending sort';
$string['strategy'] = 'Grading strategy';
$string['strategy_help'] = 'The grading strategy determines the assessment form used and the method of grading submissions. There are 4 options:

* Accumulative grading - Comments and a grade are given regarding specified aspects
* Comments - Comments are given regarding specified aspects but no grade can be given
* Number of errors - Comments and a yes/no assessment are given regarding specified assertions
* Rubric - A level assessment is given regarding specified criteria';
$string['strategyhaschanged'] = 'The workshop grading strategy has changed since the form was opened for editing.';
$string['submission'] = 'Submission';
$string['submissionattachment'] = 'Attachment';
$string['submissionby'] = 'Submission by {$a}';
$string['submissioncontent'] = 'Submission content';
$string['submissiondeleteconfirm'] = 'Are you sure you want to delete the following submission?';
$string['submissiondeleteconfirmassess'] = 'Are you sure you want to delete the following submission? Note this will also delete {$a->count} assessments associated with this submission, which may affect the reviewers\' grades.';
$string['submissionend'] = 'Submissions deadline';
$string['submissionendbeforestart'] = 'Submissions deadline can not be specified before the open for submissions date';
$string['submissionenddatetime'] = 'Submissions deadline: {$a->daydatetime} ({$a->distanceday})';
$string['submissionendevent'] = '{$a} deadline for submissions';
$string['submissionendswitch'] = 'Switch to the next phase after the submissions deadline';
$string['submissionendswitch_help'] = 'If the submissions deadline is specified and this box is checked, the workshop will automatically switch to the assessment phase after the submissions deadline.

If you enable this feature, it is recommended to set up the scheduled allocation method, too. If the submissions are not allocated, no assessment can be done even if the workshop itself is in the assessment phase.';
$string['submissiongrade'] = 'Grade for submission';
$string['submissiongrade_help'] = 'This setting specifies the maximum grade that may be obtained for submitted work.';
$string['submissiongradeof'] = 'Grade for submission (of {$a})';
$string['submissionlastmodified'] = 'Last modified';
$string['submissionrequiredcontent'] = 'You need to enter some text or add a file.';
$string['submissionrequiredfile'] = 'You need to add a file or enter some text.';
$string['submissionsallocation'] = 'Submissions allocation';
$string['submissionsettings'] = 'Submission settings';
$string['submissionsreport'] = 'Справаздача па адпраўленьням майстэрні';
$string['submissionstart'] = 'Open for submissions from';
$string['submissionstartdatetime'] = 'Open for submissions from {$a->daydatetime} ({$a->distanceday})';
$string['submissionstartevent'] = '{$a} opens for submissions';
$string['submissiontitle'] = 'Назва';
$string['submissiontypedisabled'] = 'This submission type is disabled for this workshop.';
$string['submissiontypefileavailable'] = 'File attachment<span class="accesshide"> available</span>';
$string['submissiontypefilerequired'] = '<span class="accesshide">File attachment </span>Required';
$string['submissiontypes'] = 'Submission types';
$string['submissiontypetextavailable'] = 'Online text<span class="accesshide"> available</span>';
$string['submissiontypetextrequired'] = '<span class="accesshide">Online text </span>Required';
$string['submittednotsubmitted'] = 'Submitted ({$a->submitted}) / not submitted ({$a->notsubmitted})';
$string['subplugintype_workshopallocation'] = 'Submissions allocation method';
$string['subplugintype_workshopallocation_plural'] = 'Submissions allocation methods';
$string['subplugintype_workshopeval'] = 'Grading evaluation method';
$string['subplugintype_workshopeval_plural'] = 'Grading evaluation methods';
$string['subplugintype_workshopform'] = 'Grading strategy';
$string['subplugintype_workshopform_plural'] = 'Grading strategies';
$string['switchingphase'] = 'Switching phase';
$string['switchphase'] = 'Switch phase';
$string['switchphase10'] = 'Switch to the setup phase';
$string['switchphase10info'] = 'You are about to switch the workshop into the <strong>Setup phase</strong>. In this phase, users cannot modify their submissions or their assessments. Teachers may use this phase to change workshop settings, modify the grading strategy or tweak assessment forms.';
$string['switchphase20'] = 'Switch to the submission phase';
$string['switchphase20info'] = 'You are about to switch the workshop into the <strong>Submission phase</strong>. Students may submit their work during this phase (within the submission access control dates, if set). Teachers may allocate submissions for peer review.';
$string['switchphase30'] = 'Switch to the assessment phase';
$string['switchphase30auto'] = 'Workshop will automatically switch into the assessment phase after {$a->daydatetime} ({$a->distanceday})';
$string['switchphase30info'] = 'You are about to switch the workshop into the <strong>Assessment phase</strong>. In this phase, reviewers may assess the submissions they have been allocated (within the assessment access control dates, if set).';
$string['switchphase40'] = 'Switch to the evaluation phase';
$string['switchphase40info'] = 'You are about to switch the workshop into the <strong>Grading evaluation phase</strong>. In this phase, users cannot modify their submissions or their assessments. Teachers may use the grading evaluation tools to calculate final grades and provide feedback for reviewers.';
$string['switchphase50'] = 'Close workshop';
$string['switchphase50info'] = 'You are about to close the workshop. This will result in the calculated grades appearing in the gradebook. Students may view their submissions and their submission assessments.';
$string['switchphaseauto'] = 'Switching has been scheduled';
$string['switchphasenext'] = 'Switch to the next phase';
$string['taskassesspeers'] = 'Assess peers';
$string['taskassesspeersdetails'] = 'total: {$a->total}<br />pending: {$a->todo}';
$string['taskassessself'] = 'Assess yourself';
$string['taskconclusion'] = 'Provide a conclusion of the activity';
$string['taskdone'] = 'Task done';
$string['taskfail'] = 'Task fail';
$string['taskinfo'] = 'Task info';
$string['taskinstructauthors'] = 'Provide instructions for submission';
$string['taskinstructreviewers'] = 'Provide instructions for assessment';
$string['taskintro'] = 'Set the workshop description';
$string['tasksubmit'] = 'Submit your work';
$string['tasktodo'] = 'Task to do';
$string['toolbox'] = 'Прылады майстэрні';
$string['undersetup'] = 'The workshop is currently being set up. Please wait until it is switched to the next phase.';
$string['useexamples'] = 'Use examples';
$string['useexamples_desc'] = 'Example submissions are provided for practice in assessing';
$string['useexamples_help'] = 'If enabled, users can try assessing one or more example submissions and compare their assessment with a reference assessment. The grade is not counted in the grade for assessment.';
$string['usepeerassessment'] = 'Use peer assessment';
$string['usepeerassessment_desc'] = 'Students may assess the work of others';
$string['usepeerassessment_help'] = 'If enabled, a user may be allocated submissions from other users to assess and will receive a grade for assessment in addition to a grade for their own submission.';
$string['userdatecreated'] = 'submitted on <span>{$a}</span>';
$string['userdatemodified'] = 'modified on <span>{$a}</span>';
$string['userplan'] = 'Workshop planner';
$string['userplan_help'] = 'The workshop planner displays all phases of the activity and lists the tasks for each phase. The current phase is highlighted and task completion is indicated with a tick.';
$string['userplanaccessibilityskip'] = 'Skip to current tasks';
$string['userplanaccessibilitytitle'] = 'Workshop timeline with {$a} phases';
$string['userplancurrentphase'] = 'Current phase';
$string['useselfassessment'] = 'Use self-assessment';
$string['useselfassessment_desc'] = 'Students may assess their own work';
$string['useselfassessment_help'] = 'If enabled, a user may be allocated their own submission to assess and will receive a grade for assessment in addition to a grade for their submission.';
$string['viewworkshopsummary'] = 'View workshop summary';
$string['weightinfo'] = 'Weight: {$a}';
$string['withoutsubmission'] = 'Reviewer without own submission';
$string['workshop:addinstance'] = 'Add a new workshop';
$string['workshop:allocate'] = 'Allocate submissions for review';
$string['workshop:deletesubmissions'] = 'Delete submissions';
$string['workshop:editdimensions'] = 'Edit assessment forms';
$string['workshop:exportsubmissions'] = 'Export submissions';
$string['workshop:ignoredeadlines'] = 'Ignore time restrictions';
$string['workshop:manageexamples'] = 'Manage example submissions';
$string['workshop:overridegrades'] = 'Override calculated grades';
$string['workshop:peerassess'] = 'Peer assess';
$string['workshop:publishsubmissions'] = 'Publish submissions';
$string['workshop:submit'] = 'Submit';
$string['workshop:switchphase'] = 'Switch phase';
$string['workshop:view'] = 'View workshop';
$string['workshop:viewallassessments'] = 'View all assessments';
$string['workshop:viewallsubmissions'] = 'View all submissions';
$string['workshop:viewauthornames'] = 'View author names';
$string['workshop:viewauthorpublished'] = 'View authors of published submissions';
$string['workshop:viewpublishedsubmissions'] = 'View published submissions';
$string['workshop:viewreviewernames'] = 'View reviewer names';
$string['workshopname'] = 'Workshop name';
$string['yourassessmentfor'] = 'Your assessment for {$a}';
$string['yourgrades'] = 'Вашыя адзнакі';
$string['yoursubmission'] = 'Вашае адпраўленьне';
$string['yoursubmissionwithassessments'] = 'Your submission with assessments';
