<?php
// This file is part of Moodle - https://moodle.org/
//
// Moodle is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// Moodle is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with Moodle.  If not, see <https://www.gnu.org/licenses/>.

/**
 * Strings for component 'workshop', language 'en', version '4.0'.
 *
 * @package     workshop
 * @category    string
 * @copyright   1999 Martin Dougiamas and contributors
 * @license     https://www.gnu.org/copyleft/gpl.html GNU GPL v3 or later
 */

defined('MOODLE_INTERNAL') || die();

$string['activitydate:assessmentsclose'] = 'Ацэньваньні закрываюцца:';
$string['activitydate:assessmentsclosed'] = 'Ацэньваньні закрыты:';
$string['activitydate:assessmentsopen'] = 'Ацэньваньні адкрываюцца:';
$string['activitydate:assessmentsopened'] = 'Ацэньваньні адкрыты:';
$string['activitydate:submissionsclose'] = 'Адпраўленьні закрываюцца:';
$string['activitydate:submissionsclosed'] = 'Адпраўленьні закрыты:';
$string['activitydate:submissionsopen'] = 'Адпраўленьні адкрываюцца:';
$string['activitydate:submissionsopened'] = 'Адпраўленьні адкрыты:';
$string['aggregategrades'] = 'Пераразьлічыць адзнакі';
$string['aggregation'] = 'Агрэгацыя ацэнак';
$string['allocate'] = 'Прызначыць адпраўленьні';
$string['allocatedetails'] = 'чакана: {$a->expected}<br />адпраўлена: {$a->submitted}<br />прызначана: {$a->allocate}';
$string['allocation'] = 'Прызначэньне адпраўленьняў';
$string['allocationconfigured'] = 'Прызначэньне сканфігуравана';
$string['allocationdone'] = 'Прызначэньне зроблена';
$string['allocationerror'] = 'Памылка прызначэньня';
$string['allowedfiletypesforoverallfeedback'] = 'Дазволеныя тыпы файлаў для ўкладаньняў водгукаў';
$string['allowedfiletypesforoverallfeedback_help'] = 'Тыпы файлаў для ўкладаньняў водгукаў льга абмежаваць вызначаным сьпісам дазволеных файлаў. Калі поле пакінуць пустым, тады ўсе тыпы файлаў будуць дазволены.';
$string['allowedfiletypesforoverallfeedback_link'] = 'admin/tool/filetypes/index';
$string['allowedfiletypesforsubmission'] = 'Дазволеныя тыпы файлаў для ўкладаньняў адпраўленьняў';
$string['allowedfiletypesforsubmission_help'] = 'Тыпы файлаў для ўкладаньняў адпраўленьняў льга абмежаваць вызначаным сьпісам дазволеных файлаў. Калі поле пакінуць пустым, тады ўсе тыпы файлаў будуць дазволены.';
$string['allowedfiletypesforsubmission_link'] = 'admin/tool/filetypes/index';
$string['allsubmissions'] = 'Усе адпраўленьні ({$a})';
$string['alreadygraded'] = 'Ужо ацэнена';
$string['areaconclusion'] = 'Тэкст высновы';
$string['areainstructauthors'] = 'Інструкцыі для адпраўленьня';
$string['areainstructreviewers'] = 'Інструкцыі для ацэньваньня';
$string['areaoverallfeedbackattachment'] = 'Выніковыя ўкладаньні водгукаў';
$string['areaoverallfeedbackcontent'] = 'Выніковыя тэксты водгукаў';
$string['areasubmissionattachment'] = 'Укладаньні адпраўленьня';
$string['areasubmissioncontent'] = 'Тэксты адпраўленьня';
$string['assess'] = 'Ацаніць';
$string['assessedexample'] = 'Ацэненае прыкладнае адпраўленьне';
$string['assessedsubmission'] = 'Ацэненае адпраўленьне';
$string['assessingexample'] = 'Ацэньваньне прыкладнага адпраўленьня';
$string['assessingsubmission'] = 'Ацэньваньне адпраўленьня';
$string['assessment'] = 'Ацэньваньне';
$string['assessmentby'] = 'ацаніў(ла) <a href="{$a->url}">{$a->name}</a>';
$string['assessmentbyfullname'] = 'Ацаніў(ла) {$a}';
$string['assessmentbyyourself'] = 'Вашае ацэньваньне';
$string['assessmentdeleted'] = 'Ацэньваньне адмацавана';
$string['assessmentend'] = 'Апошні тэрмін ацэньваньня';
$string['assessmentendbeforestart'] = 'Апошні тэрмін ацэньваньня ня можа быць усталяваным ранейшым за дату адкрыцьця ацэньваньня';
$string['assessmentenddatetime'] = 'Апошні тэрмін ацэньваньня: {$a->daydatetime} ({$a->distanceday})';
$string['assessmentendevent'] = 'Апошні тэрмін ацэньваньня {$a}';
$string['assessmentform'] = 'Форма ацэньваньня';
$string['assessmentofsubmission'] = '<a href="{$a->assessmenturl}">Ацэньваньне</a> <a href="{$a->submissionurl}">{$a->submissiontitle}</a>';
$string['assessmentreference'] = 'Эталоннае ацэньваньне';
$string['assessmentreferenceconflict'] = 'Нельга ацаніць прыкладнае адпраўленьне, дзеля якога вы падалі эталоннае ацэньваньне.';
$string['assessmentreferenceneeded'] = 'Вы ацанілі гэтае прыкладнае адпраўленьне, каб падаць эталоннае ацэньваньне. Націсьніце кнопку \'Працягнуць\', каб ацаніць адпраўленьне.';
$string['assessments'] = 'Ацэньваньні';
$string['assessmentsettings'] = 'Налады ацэньваньня';
$string['assessmentstart'] = 'Адкрыцьцё ацэньваньня з';
$string['assessmentstartdatetime'] = 'Адкрыцьцё ацэньваньня з {$a->daydatetime} ({$a->distanceday})';
$string['assessmentstartevent'] = 'Ацэньваньне адкрываецца {$a}';
$string['assessmentweight'] = 'Вага ацэньваньня';
$string['assignedassessments'] = 'Прызначаныя адпраўленьні дзеля ацэньваньня';
$string['assignedassessmentsnone'] = 'Вы ня маеце прызначаных адпраўленьняў на ацэньваньне';
$string['backtoeditform'] = 'Назад да рэдагаваньня формы';
$string['byfullname'] = '<a href="{$a->url}">{$a->name}</a>';
$string['byfullnamewithoutlink'] = '{$a}';
$string['calculategradinggrades'] = 'Разьлічыць адзнакі ацэньваньняў';
$string['calculategradinggradesdetails'] = 'чакана: {$a->expected}<br />разьлічана: {$a->calculated}';
$string['calculatesubmissiongrades'] = 'Разьлічыць адзнакі адпраўленьняў';
$string['calculatesubmissiongradesdetails'] = 'чакана: {$a->expected}<br />разьлічана: {$a->calculated}';
$string['chooseuser'] = 'Абраць карыстальніка...';
$string['clearaggregatedgrades'] = 'Ачысьціць усе агрэганаваныя адзнакі';
$string['clearaggregatedgrades_help'] = 'Агрэганаваныя адзнакі за адпраўленьні і ацэньваньні будуць скінуты. Вы можаце пераразьлічыць гэтыя адзнакі з нуля на этапе ацэньваньня.';
$string['clearaggregatedgradesconfirm'] = 'Вы ўпэўнены, што жадаеце ачысьціць разьлічаныя адзнакі за адпраўленьні і ацэньваньні?';
$string['clearassessments'] = 'Ачысьціць ацэньваньні';
$string['clearassessments_help'] = 'Разьлічаныя адзнакі за адпраўленьні і ацэньваньні будуць скінуты. Інфармацыя пра тое, як былі запоўнены формы ацэньваньня, дагэтуль захоўваецца, але ўсе рэцэнзенты мусяць наноў адкрыць форму ацэньваньня і перазахаваць яе, каб зноў атрымаць разьлічаныя адзнакі.';
$string['clearassessmentsconfirm'] = 'Вы ўпэўнены, што жадаеце ацысьціць усе адзнакі ацэньваньня? Вы ня зможаце вярнуць інфармацыю самастойна, рэцэнзенты будуць вымушаны ацаніць прызначаныя адпраўленьні наноў.';
$string['conclusion'] = 'Выснова';
$string['conclusion_help'] = 'Тэкст высновы паказваецца ўдзельнікам напрыканцы актыўнасьці.';
$string['configexamplesmode'] = 'Стандартны рэжым прыкладных ацэньваньняў у майстэрнях';
$string['configgrade'] = 'Стандартная максімальная адзнака для адпраўленьняў у майстэрнях';
$string['configgradedecimals'] = 'Стандартная колькасьць лічбаў, якая мусіць адлюстроўвацца пасьля дзесятковай кропкі падчас адлюстраваньня адзнак.';
$string['configgradinggrade'] = 'Стандартная максімальная адзнака для ацэньваньняў у майстэрнях';
$string['configmaxbytes'] = 'Стандартны максімальны памер файлаў адпраўленьняў дзеля ўсіх майстэрняў на сайце (з улікам абмежаваньняў курса і іншых лакальных наладаў)';
$string['configstrategy'] = 'Стандартная стратэгія ацэньваньня ў майстэрнях';
$string['createsubmission'] = 'Дадаць адпраўленьне';
$string['crontask'] = 'Фонавая апрацоўка модуля майстэрня';
$string['daysago'] = '{$a} дзён таму';
$string['daysleft'] = '{$a} дзён засталося';
$string['daystoday'] = 'сёньня';
$string['daystomorrow'] = 'заўтра';
$string['daysyesterday'] = 'учора';
$string['deadlinesignored'] = 'Часовыя абмежаваньні на вас не распаўсюджваюцца';
$string['deletesubmission'] = 'Выдаліць адпраўленьне';
$string['editassessmentform'] = 'Рэдагаваць форму ацэньваньня';
$string['editassessmentformstrategy'] = 'Рэдагаваць форму ацэньваньня ({$a})';
$string['editingassessmentform'] = 'Рэдагаваньне формы ацэньваньня';
$string['editingsubmission'] = 'Рэдагаваньне адпраўленьня';
$string['editsubmission'] = 'Рэдагаваць адпраўленьне';
$string['err_multiplesubmissions'] = 'Падчас рэдагаваньня гэтай формы, іншая версія адпраўленьня была захавана. Шматразовыя адпраўленьні адным карыстальнікам забаронены.';
$string['err_removegrademappings'] = 'Нельга выдаліць нявыкарыстаныя параўнаньні адзнак';
$string['evaluategradeswait'] = 'Калі ласка, пачакайце, пакуль адзнакі будуць ацэнены і разьлічаны';
$string['evaluation'] = 'Ацэньваньне адзнак';
$string['evaluationmethod'] = 'Метад ацэньваньня адзнак';
$string['evaluationmethod_help'] = 'Метад ацэньваньня адзнак вызначае, як будуць разьлічвацца адзнакі ацэньваньняў. Вы можаце дазволіць яму неаднаразова пераразьлічваць адзнакі з рознымі наладамі, пакуль вас не задаволіць вынік.';
$string['evaluationsettings'] = 'Налады ацэньваньня адзнак';
$string['eventassessableuploaded'] = 'Адпраўленьне было запампована.';
$string['eventassessmentevaluated'] = 'Ацэньваньне ацэнена';
$string['eventassessmentevaluationsreset'] = 'Ацэньваньне ацэньваньня скінута';
$string['eventassessmentreevaluated'] = 'Ацэньваньне пераацэнена';
$string['eventphaseautomaticallyswitched'] = 'Этап аўтаматычна пераключаны';
$string['eventphaseswitched'] = 'Этап пераключаны';
$string['eventsubmissionassessed'] = 'Адпраўленьне ацэнена';
$string['eventsubmissionassessmentsreset'] = 'Ацэньваньне адпраўленьня ачышчана';
$string['eventsubmissioncreated'] = 'Адпраўленьне створана';
$string['eventsubmissiondeleted'] = 'Адпраўленьне выдалена';
$string['eventsubmissionreassessed'] = 'Адпраўленьне пераацэнена';
$string['eventsubmissionupdated'] = 'Адпраўленьне абноўлена';
$string['eventsubmissionviewed'] = 'Адпраўленьне прагледжана';
$string['example'] = 'Прыкладнае адпраўленьне';
$string['exampleadd'] = 'Дадаць прыкладнае адпраўленьне';
$string['exampleassess'] = 'Assess example submission';
$string['exampleassessments'] = 'Example submissions to assess';
$string['exampleassesstask'] = 'Assess examples';
$string['exampleassesstaskdetails'] = 'expected: {$a->expected}<br />assessed: {$a->assessed}';
$string['examplecomparing'] = 'Comparing assessments of example submission';
$string['exampledelete'] = 'Delete example';
$string['exampledeleteconfirm'] = 'Are you sure you want to delete the following example submission? Click \'Continue\' button to delete the submission.';
$string['exampleedit'] = 'Edit example';
$string['exampleediting'] = 'Editing example';
$string['exampleneedassessed'] = 'You have to assess all example submissions first';
$string['exampleneedsubmission'] = 'You have to submit your work and assess all example submissions first';
$string['examplesbeforeassessment'] = 'Examples are available after own submission and must be assessed before peer assessment';
$string['examplesbeforesubmission'] = 'Examples must be assessed before own submission';
$string['examplesmode'] = 'Mode of examples assessment';
$string['examplesubmissions'] = 'Example submissions';
$string['examplesvoluntary'] = 'Assessment of example submission is voluntary';
$string['exportsubmission'] = 'Export this page';
$string['feedbackauthor'] = 'Feedback for the author';
$string['feedbackauthorattachment'] = 'Attachment';
$string['feedbackby'] = 'Feedback by {$a}';
$string['feedbackreviewer'] = 'Feedback for the reviewer';
$string['feedbacksettings'] = 'Feedback';
$string['formataggregatedgrade'] = '{$a->grade}';
$string['formataggregatedgradeover'] = '<del>{$a->grade}</del><br /><ins>{$a->over}</ins>';
$string['formatpeergrade'] = '<span class="grade">{$a->grade}</span> <span class="gradinggrade">({$a->gradinggrade})</span>';
$string['formatpeergradeover'] = '<span class="grade">{$a->grade}</span> <span class="gradinggrade">(<del>{$a->gradinggrade}</del> / <ins>{$a->gradinggradeover}</ins>)</span>';
$string['formatpeergradeoverweighted'] = '<span class="grade">{$a->grade}</span> <span class="gradinggrade">(<del>{$a->gradinggrade}</del> / <ins>{$a->gradinggradeover}</ins>)</span> @ <span class="weight">{$a->weight}</span>';
$string['formatpeergradeweighted'] = '<span class="grade">{$a->grade}</span> <span class="gradinggrade">({$a->gradinggrade})</span> @ <span class="weight">{$a->weight}</span>';
$string['givengrades'] = 'Grades given';
$string['grade_grading_name'] = 'Assessment';
$string['grade_submission_name'] = 'Submission';
$string['gradecalculated'] = 'Calculated grade for submission';
$string['gradedecimals'] = 'Decimal places in grades';
$string['gradegivento'] = '&gt;';
$string['gradeinfo'] = 'Grade: {$a->received} of {$a->max}';
$string['gradeitemassessment'] = '{$a->workshopname} (assessment)';
$string['gradeitemsubmission'] = '{$a->workshopname} (submission)';
$string['gradeover'] = 'Override grade for submission';
$string['gradereceivedfrom'] = '&lt;';
$string['gradesreport'] = 'Workshop grades report';
$string['gradetopassgrading'] = 'Assessment grade to pass';
$string['gradetopasssubmission'] = 'Submission grade to pass';
$string['gradinggrade'] = 'Grade for assessment';
$string['gradinggrade_help'] = 'This setting specifies the maximum grade that may be obtained for submission assessment.';
$string['gradinggradecalculated'] = 'Calculated grade for assessment';
$string['gradinggradeof'] = 'Grade for assessment (of {$a})';
$string['gradinggradeover'] = 'Override grade for assessment';
$string['gradingsettings'] = 'Grading settings';
$string['groupnoallowed'] = 'You are not allowed to access any group in this workshop';
$string['iamsure'] = 'Yes, I am sure';
$string['indicator:cognitivedepth'] = 'Workshop cognitive';
$string['indicator:cognitivedepth_help'] = 'This indicator is based on the cognitive depth reached by the student in a Workshop activity.';
$string['indicator:cognitivedepthdef'] = 'Workshop cognitive';
$string['indicator:cognitivedepthdef_help'] = 'The participant has reached this percentage of the cognitive engagement offered by the Workshop activities during this analysis interval (Levels = No view, View, Submit, View feedback, Comment on feedback, Resubmit after viewing feedback)';
$string['indicator:cognitivedepthdef_link'] = 'Learning_analytics_indicators#Cognitive_depth';
$string['indicator:socialbreadth'] = 'Workshop social';
$string['indicator:socialbreadth_help'] = 'This indicator is based on the social breadth reached by the student in a Workshop activity.';
$string['indicator:socialbreadthdef'] = 'Workshop social';
$string['indicator:socialbreadthdef_help'] = 'The participant has reached this percentage of the social engagement offered by the Workshop activities during this analysis interval (Levels = No participation, Participant alone, Participant with others)';
$string['indicator:socialbreadthdef_link'] = 'Learning_analytics_indicators#Social_breadth';
$string['info'] = 'Info';
$string['instructauthors'] = 'Instructions for submission';
$string['instructreviewers'] = 'Instructions for assessment';
$string['introduction'] = 'Description';
$string['latesubmissions'] = 'Late submissions';
$string['latesubmissions_desc'] = 'Allow submissions after the deadline';
$string['latesubmissions_help'] = 'If enabled, an author may submit their work after the submissions deadline or during the assessment phase. Late submissions cannot be edited though.';
$string['latesubmissionsallowed'] = 'Late submissions are allowed';
$string['legacyallocationplugincron'] = 'Legacy cron workshop allocation';
$string['maxbytes'] = 'Maximum submission attachment size';
$string['modulename'] = 'Workshop';
$string['modulename_help'] = 'The workshop activity module enables the collection, review and peer assessment of students\' work.

Students can submit any digital content (files), such as word-processed documents or spreadsheets and can also type text directly into a field using the text editor.

Submissions are assessed using a multi-criteria assessment form defined by the teacher. The process of peer assessment and understanding the assessment form can be practised in advance with example submissions provided by the teacher, together with a reference assessment. Students are given the opportunity to assess one or more of their peers\' submissions. Submissions and reviewers may be anonymous if required.

Students obtain two grades in a workshop activity - a grade for their submission and a grade for their assessment of their peers\' submissions. Both grades are recorded in the gradebook.';
$string['modulename_link'] = 'mod/workshop/view';
$string['modulenameplural'] = 'Workshops';
$string['myassessments'] = 'My assessments';
$string['mysubmission'] = 'My submission';
$string['nattachments'] = 'Maximum number of submission attachments';
$string['noexamples'] = 'No examples yet in this workshop';
$string['noexamplesformready'] = 'You must define the assessment form before providing example submissions';
$string['nogradeyet'] = 'No grade yet';
$string['nosubmissionfound'] = 'No submission found for this user';
$string['nosubmissions'] = 'No submissions yet in this workshop';
$string['nosubmissiontype'] = 'At least one submission type must be available';
$string['notassessed'] = 'Not assessed yet';
$string['nothingfound'] = 'Nothing to display';
$string['nothingtoreview'] = 'Nothing to review';
$string['notoverridden'] = 'Not overridden';
$string['noworkshops'] = 'There are no workshops in this course';
$string['noyoursubmission'] = 'You have not submitted your work yet';
$string['nullgrade'] = '-';
$string['overallfeedback'] = 'Overall feedback';
$string['overallfeedbackfiles'] = 'Maximum number of overall feedback attachments';
$string['overallfeedbackmaxbytes'] = 'Maximum overall feedback attachment size';
$string['overallfeedbackmode'] = 'Overall feedback mode';
$string['overallfeedbackmode_0'] = 'Disabled';
$string['overallfeedbackmode_1'] = 'Enabled and optional';
$string['overallfeedbackmode_2'] = 'Enabled and required';
$string['overallfeedbackmode_help'] = 'If enabled, a text field is displayed at the bottom of the assessment form. Reviewers can put the overall assessment of the submission there, or provide additional explanation of their assessment.';
$string['page-mod-workshop-x'] = 'Any workshop module page';
$string['participant'] = 'Participant';
$string['participantrevierof'] = 'Participant is reviewer of';
$string['participantreviewedby'] = 'Participant is reviewed by';
$string['phaseassessment'] = 'Assessment phase';
$string['phaseclosed'] = 'Closed';
$string['phaseevaluation'] = 'Grading evaluation phase';
$string['phasesetup'] = 'Setup phase';
$string['phasesoverlap'] = 'The submission phase and the assessment phase can not overlap';
$string['phasesubmission'] = 'Submission phase';
$string['pluginadministration'] = 'Workshop administration';
$string['pluginname'] = 'Workshop';
$string['prepareexamples'] = 'Prepare example submissions';
$string['previewassessmentform'] = 'Preview';
$string['privacy:metadata:aggregatedgradinggrade'] = 'Aggregated grade for all assessments made by the user in the given workshop activity';
$string['privacy:metadata:assessmentgrade'] = 'Aggregated grade for the submission suggested by this assessment';
$string['privacy:metadata:assessmentgradinggrade'] = 'Grade for providing this assessment';
$string['privacy:metadata:assessmentgradinggradeover'] = 'Manually overridden value of the grade for providing this assessment';
$string['privacy:metadata:assessmentid'] = 'ID of the assessment';
$string['privacy:metadata:authorid'] = 'ID of the submission author';
$string['privacy:metadata:dimensiongrade'] = 'Grade in the given assessment dimension';
$string['privacy:metadata:dimensionid'] = 'ID of the assessment dimension';
$string['privacy:metadata:example'] = 'Whether this record represents an example submission';
$string['privacy:metadata:feedbackauthor'] = 'Feedback for the author';
$string['privacy:metadata:feedbackauthorformat'] = 'Text format of the feedback for the author';
$string['privacy:metadata:feedbackreviewer'] = 'Feedback for the user providing the assessment';
$string['privacy:metadata:feedbackreviewerformat'] = 'Text format of the feedback for the user providing the assessment';
$string['privacy:metadata:late'] = 'Whether the submission been submitted after the deadline';
$string['privacy:metadata:peercomment'] = 'Comment on the given grade by the user providing the assessment';
$string['privacy:metadata:peercommentformat'] = 'Text format of the comment on the given grade';
$string['privacy:metadata:preference:perpage'] = 'Number of submissions the user prefers to see on one page';
$string['privacy:metadata:preference:viewlet-allexamples-collapsed'] = 'The collapsed/expanded state for the \'Example submissions\' viewlet.';
$string['privacy:metadata:preference:viewlet-allsubmissions-collapsed'] = 'The collapsed/expanded state for the \'Workshop submissions report\' viewlet.';
$string['privacy:metadata:preference:viewlet-assessmentform-collapsed'] = 'The collapsed/expanded state for the \'Assessment form\' viewlet.';
$string['privacy:metadata:preference:viewlet-assignedassessments-collapsed'] = 'The collapsed/expanded state for the \'Assigned submissions to assess\' viewlet.';
$string['privacy:metadata:preference:viewlet-cleargrades-collapsed'] = 'The collapsed/expanded state for the \'Workshop toolbox\' viewlet.';
$string['privacy:metadata:preference:viewlet-conclusion-collapsed'] = 'The collapsed/expanded state for the \'Conclusion\' viewlet.';
$string['privacy:metadata:preference:viewlet-examples-collapsed'] = 'The collapsed/expanded state for the \'Example submissions to assess\' viewlet.';
$string['privacy:metadata:preference:viewlet-examplesfail-collapsed'] = 'The collapsed/expanded state for the \'Example submissions to assess\' viewlet.';
$string['privacy:metadata:preference:viewlet-gradereport-collapsed'] = 'The collapsed/expanded state for the \'Workshop grades report\' viewlet.';
$string['privacy:metadata:preference:viewlet-instructauthors-collapsed'] = 'The collapsed/expanded state for the \'Instructions for submission\' viewlet.';
$string['privacy:metadata:preference:viewlet-instructreviewers-collapsed'] = 'The collapsed/expanded state for the \'Instructions for assessment\' viewlet.';
$string['privacy:metadata:preference:viewlet-intro-collapsed'] = 'The collapsed/expanded state for the \'Intro\' viewlet.';
$string['privacy:metadata:preference:viewlet-overallfeedback-collapsed'] = 'The collapsed/expanded state for the \'Overall feedback\' viewlet.';
$string['privacy:metadata:preference:viewlet-ownsubmission-collapsed'] = 'The collapsed/expanded state for the \'Your submission\' viewlet.';
$string['privacy:metadata:preference:viewlet-publicsubmissions-collapsed'] = 'The collapsed/expanded state for the \'Published submissions\' viewlet.';
$string['privacy:metadata:preference:viewlet-yourgrades-collapsed'] = 'The collapsed/expanded state for the \'Your grades\' viewlet.';
$string['privacy:metadata:published'] = 'Whether the submission should be published to all participants once the workshop is closed';
$string['privacy:metadata:reviewerid'] = 'ID of the user providing the assessment';
$string['privacy:metadata:strategy'] = 'Name of the grading strategy subplugin interpreting the record values';
$string['privacy:metadata:submissioncontent'] = 'Content of the submission';
$string['privacy:metadata:submissioncontentformat'] = 'Text format of the submission content';
$string['privacy:metadata:submissiongrade'] = 'Aggregated grade for the submission written as a decimal number from interval 0..100';
$string['privacy:metadata:submissiongradeover'] = 'Manually overridden value of the aggregated grade';
$string['privacy:metadata:submissionid'] = 'ID of the submission';
$string['privacy:metadata:submissiontitle'] = 'Title of the submission';
$string['privacy:metadata:subsystem:corefiles'] = 'Workshop module stores files embedded in / attached to the submission text';
$string['privacy:metadata:subsystem:coreplagiarism'] = 'Workshop module has inbuilt support for plagiarism prevention systems';
$string['privacy:metadata:timeaggregated'] = 'When the aggregated grade was last calculated';
$string['privacy:metadata:timecreated'] = 'When this record was created in the database';
$string['privacy:metadata:timemodified'] = 'When this record was last modified in the database';
$string['privacy:metadata:userid'] = 'ID of the user for which aggregated grade is calculated';
$string['privacy:metadata:weight'] = 'Weight of the assessment';
$string['privacy:metadata:workshopaggregations'] = 'Holds aggregated grades for assessment';
$string['privacy:metadata:workshopassessments'] = 'Holds information about allocated assessments of workshop module submissions';
$string['privacy:metadata:workshopgrades'] = 'Holds information about how the assessment forms were filled with grades and comments';
$string['privacy:metadata:workshopid'] = 'ID of the workshop activity';
$string['privacy:metadata:workshopsubmissions'] = 'Holds information about workshop module submissions';
$string['privacy:request:delete:content'] = 'The content has been deleted (requested by the user or expired)';
$string['privacy:request:delete:title'] = '[Deleted]';
$string['publishedsubmissions'] = 'Published submissions';
$string['publishsubmission'] = 'Publish submission';
$string['publishsubmission_help'] = 'Published submissions are available to the others when the workshop is closed.';
$string['reassess'] = 'Re-assess';
$string['receivedgrades'] = 'Grades received';
$string['recentassessments'] = 'Workshop assessments:';
$string['recentsubmissions'] = 'Workshop submissions:';
$string['resetassessments'] = 'Delete all assessments';
$string['resetassessments_help'] = 'You can choose to delete just allocated assessments without affecting submissions. If submissions are to be deleted, their assessments will be deleted implicitly and this option is ignored. Note this also includes assessments of example submissions.';
$string['resetphase'] = 'Switch to the setup phase';
$string['resetphase_help'] = 'If enabled, all workshops will be put into the initial setup phase.';
$string['resetsubmissions'] = 'Delete all submissions';
$string['resetsubmissions_help'] = 'All the submissions and their assessments will be deleted. This does not affect example submissions.';
$string['saveandclose'] = 'Save and close';
$string['saveandcontinue'] = 'Save and continue editing';
$string['saveandpreview'] = 'Save and preview';
$string['saveandshownext'] = 'Save and show next';
$string['search:activity'] = 'Workshop - activity information';
$string['selfassessmentdisabled'] = 'Self-assessment disabled';
$string['showingperpage'] = 'Showing {$a} items per page';
$string['showingperpagechange'] = 'Change ...';
$string['someuserswosubmission'] = 'There is at least one author who has not yet submitted their work';
$string['sortasc'] = 'Ascending sort';
$string['sortdesc'] = 'Descending sort';
$string['strategy'] = 'Grading strategy';
$string['strategy_help'] = 'The grading strategy determines the assessment form used and the method of grading submissions. There are 4 options:

* Accumulative grading - Comments and a grade are given regarding specified aspects
* Comments - Comments are given regarding specified aspects but no grade can be given
* Number of errors - Comments and a yes/no assessment are given regarding specified assertions
* Rubric - A level assessment is given regarding specified criteria';
$string['strategyhaschanged'] = 'The workshop grading strategy has changed since the form was opened for editing.';
$string['submission'] = 'Submission';
$string['submissionattachment'] = 'Attachment';
$string['submissionby'] = 'Submission by {$a}';
$string['submissioncontent'] = 'Submission content';
$string['submissiondeleteconfirm'] = 'Are you sure you want to delete the following submission?';
$string['submissiondeleteconfirmassess'] = 'Are you sure you want to delete the following submission? Note this will also delete {$a->count} assessments associated with this submission, which may affect the reviewers\' grades.';
$string['submissionend'] = 'Submissions deadline';
$string['submissionendbeforestart'] = 'Submissions deadline can not be specified before the open for submissions date';
$string['submissionenddatetime'] = 'Submissions deadline: {$a->daydatetime} ({$a->distanceday})';
$string['submissionendevent'] = '{$a} deadline for submissions';
$string['submissionendswitch'] = 'Switch to the next phase after the submissions deadline';
$string['submissionendswitch_help'] = 'If the submissions deadline is specified and this box is checked, the workshop will automatically switch to the assessment phase after the submissions deadline.

If you enable this feature, it is recommended to set up the scheduled allocation method, too. If the submissions are not allocated, no assessment can be done even if the workshop itself is in the assessment phase.';
$string['submissiongrade'] = 'Grade for submission';
$string['submissiongrade_help'] = 'This setting specifies the maximum grade that may be obtained for submitted work.';
$string['submissiongradeof'] = 'Grade for submission (of {$a})';
$string['submissionlastmodified'] = 'Last modified';
$string['submissionrequiredcontent'] = 'You need to enter some text or add a file.';
$string['submissionrequiredfile'] = 'You need to add a file or enter some text.';
$string['submissionsallocation'] = 'Submissions allocation';
$string['submissionsettings'] = 'Submission settings';
$string['submissionsreport'] = 'Workshop submissions report';
$string['submissionstart'] = 'Open for submissions from';
$string['submissionstartdatetime'] = 'Open for submissions from {$a->daydatetime} ({$a->distanceday})';
$string['submissionstartevent'] = '{$a} opens for submissions';
$string['submissiontitle'] = 'Title';
$string['submissiontypedisabled'] = 'This submission type is disabled for this workshop.';
$string['submissiontypefileavailable'] = 'File attachment<span class="accesshide"> available</span>';
$string['submissiontypefilerequired'] = '<span class="accesshide">File attachment </span>Required';
$string['submissiontypes'] = 'Submission types';
$string['submissiontypetextavailable'] = 'Online text<span class="accesshide"> available</span>';
$string['submissiontypetextrequired'] = '<span class="accesshide">Online text </span>Required';
$string['submittednotsubmitted'] = 'Submitted ({$a->submitted}) / not submitted ({$a->notsubmitted})';
$string['subplugintype_workshopallocation'] = 'Submissions allocation method';
$string['subplugintype_workshopallocation_plural'] = 'Submissions allocation methods';
$string['subplugintype_workshopeval'] = 'Grading evaluation method';
$string['subplugintype_workshopeval_plural'] = 'Grading evaluation methods';
$string['subplugintype_workshopform'] = 'Grading strategy';
$string['subplugintype_workshopform_plural'] = 'Grading strategies';
$string['switchingphase'] = 'Switching phase';
$string['switchphase'] = 'Switch phase';
$string['switchphase10'] = 'Switch to the setup phase';
$string['switchphase10info'] = 'You are about to switch the workshop into the <strong>Setup phase</strong>. In this phase, users cannot modify their submissions or their assessments. Teachers may use this phase to change workshop settings, modify the grading strategy or tweak assessment forms.';
$string['switchphase20'] = 'Switch to the submission phase';
$string['switchphase20info'] = 'You are about to switch the workshop into the <strong>Submission phase</strong>. Students may submit their work during this phase (within the submission access control dates, if set). Teachers may allocate submissions for peer review.';
$string['switchphase30'] = 'Switch to the assessment phase';
$string['switchphase30auto'] = 'Workshop will automatically switch into the assessment phase after {$a->daydatetime} ({$a->distanceday})';
$string['switchphase30info'] = 'You are about to switch the workshop into the <strong>Assessment phase</strong>. In this phase, reviewers may assess the submissions they have been allocated (within the assessment access control dates, if set).';
$string['switchphase40'] = 'Switch to the evaluation phase';
$string['switchphase40info'] = 'You are about to switch the workshop into the <strong>Grading evaluation phase</strong>. In this phase, users cannot modify their submissions or their assessments. Teachers may use the grading evaluation tools to calculate final grades and provide feedback for reviewers.';
$string['switchphase50'] = 'Close workshop';
$string['switchphase50info'] = 'You are about to close the workshop. This will result in the calculated grades appearing in the gradebook. Students may view their submissions and their submission assessments.';
$string['switchphaseauto'] = 'Switching has been scheduled';
$string['switchphasenext'] = 'Switch to the next phase';
$string['taskassesspeers'] = 'Assess peers';
$string['taskassesspeersdetails'] = 'total: {$a->total}<br />pending: {$a->todo}';
$string['taskassessself'] = 'Assess yourself';
$string['taskconclusion'] = 'Provide a conclusion of the activity';
$string['taskdone'] = 'Task done';
$string['taskfail'] = 'Task fail';
$string['taskinfo'] = 'Task info';
$string['taskinstructauthors'] = 'Provide instructions for submission';
$string['taskinstructreviewers'] = 'Provide instructions for assessment';
$string['taskintro'] = 'Set the workshop description';
$string['tasksubmit'] = 'Submit your work';
$string['tasktodo'] = 'Task to do';
$string['toolbox'] = 'Workshop toolbox';
$string['undersetup'] = 'The workshop is currently being set up. Please wait until it is switched to the next phase.';
$string['useexamples'] = 'Use examples';
$string['useexamples_desc'] = 'Example submissions are provided for practice in assessing';
$string['useexamples_help'] = 'If enabled, users can try assessing one or more example submissions and compare their assessment with a reference assessment. The grade is not counted in the grade for assessment.';
$string['usepeerassessment'] = 'Use peer assessment';
$string['usepeerassessment_desc'] = 'Students may assess the work of others';
$string['usepeerassessment_help'] = 'If enabled, a user may be allocated submissions from other users to assess and will receive a grade for assessment in addition to a grade for their own submission.';
$string['userdatecreated'] = 'submitted on <span>{$a}</span>';
$string['userdatemodified'] = 'modified on <span>{$a}</span>';
$string['userplan'] = 'Workshop planner';
$string['userplan_help'] = 'The workshop planner displays all phases of the activity and lists the tasks for each phase. The current phase is highlighted and task completion is indicated with a tick.';
$string['userplanaccessibilityskip'] = 'Skip to current tasks';
$string['userplanaccessibilitytitle'] = 'Workshop timeline with {$a} phases';
$string['userplancurrentphase'] = 'Current phase';
$string['useselfassessment'] = 'Use self-assessment';
$string['useselfassessment_desc'] = 'Students may assess their own work';
$string['useselfassessment_help'] = 'If enabled, a user may be allocated their own submission to assess and will receive a grade for assessment in addition to a grade for their submission.';
$string['viewworkshopsummary'] = 'View workshop summary';
$string['weightinfo'] = 'Weight: {$a}';
$string['withoutsubmission'] = 'Reviewer without own submission';
$string['workshop:addinstance'] = 'Add a new workshop';
$string['workshop:allocate'] = 'Allocate submissions for review';
$string['workshop:deletesubmissions'] = 'Delete submissions';
$string['workshop:editdimensions'] = 'Edit assessment forms';
$string['workshop:exportsubmissions'] = 'Export submissions';
$string['workshop:ignoredeadlines'] = 'Ignore time restrictions';
$string['workshop:manageexamples'] = 'Manage example submissions';
$string['workshop:overridegrades'] = 'Override calculated grades';
$string['workshop:peerassess'] = 'Peer assess';
$string['workshop:publishsubmissions'] = 'Publish submissions';
$string['workshop:submit'] = 'Submit';
$string['workshop:switchphase'] = 'Switch phase';
$string['workshop:view'] = 'View workshop';
$string['workshop:viewallassessments'] = 'View all assessments';
$string['workshop:viewallsubmissions'] = 'View all submissions';
$string['workshop:viewauthornames'] = 'View author names';
$string['workshop:viewauthorpublished'] = 'View authors of published submissions';
$string['workshop:viewpublishedsubmissions'] = 'View published submissions';
$string['workshop:viewreviewernames'] = 'View reviewer names';
$string['workshopname'] = 'Workshop name';
$string['yourassessmentfor'] = 'Your assessment for {$a}';
$string['yourgrades'] = 'Your grades';
$string['yoursubmission'] = 'Your submission';
$string['yoursubmissionwithassessments'] = 'Your submission with assessments';
